`文档版本：1.1.0`    `更新日期：2021.06.04`

# 一、投资研究功能介绍

欢迎您使用 iQuant 提供的投资研究功能，本功能基于 Jupyter Notebook 构建，支持灵活的图表处理、数据处理、文本输出等，非常适合探索、试验及数据分析。

> **Jupyter Notebook 简介**
>
> Jupyter Notebook 是一个开源的 Web 应用程序，允许用户创建和共享包含代码、方程式、可视化和文本的文档。它的用途包括：数据清理和转换、数值模拟、统计建模、数据可视化、机器学习等等。
>
> 它提供了一个环境，你可以在其中记录代码，运行代码，查看结果，可视化数据并在查看输出结果。这些特性使其成为一款执行端到端数据科学工作流程的便捷工具 ，可以用于数据清理，统计建模，构建和训练机器学习模型，可视化数据以及许多其他用途。
>
> 当你还在构建项目原型时，Jupyter Notebook 真的特别好用，因为你的代码是被写入独立的单元中并被单独执行的。这允许用户测试项目中的特定代码块，而无需从脚本的开始执行代码。许多其他的 IDE 环境（如 RStudio ）也以其他几种方式做到这一点。
>
> 注：
>
> - 本指引只对 Jupyter Notebook 中，与 **iQuant** 相关的部分进行操作指引，关于 Jupyter Notebook 更加详细的说明文档或者操作教程，可以在其官网或搜索引擎上找到丰富的资料。
> - Jupyter Notebook 官方文档链接：https://jupyter-notebook.readthedocs.io/en/stable/

目前，投资研究模块将 Jupyter Notebook 与 iQuant 部分接口打通，在 Jupyter Notebook 中可以直接调用 iQuant 提供的接口函数，从而提取数据或者使用专用的函数进行投资研究。

投资研究环境与策略开发环境的区别：

| 区别     | 策略开发环境                                                 | 投资研究环境                                                 |
| :------- | :----------------------------------------------------------- | :----------------------------------------------------------- |
| 结构区别 | 策略开发环境中编写模型或者使用API函数，需要遵循本平台规定的结构，必须实现两个接口：init() 与 handlebar() ，在此基础上，才能调用本平台封装好的 API 函数进行运行或者回测（详见 Python API 文档） | 投资研究环境的单元格内可直接使用本平台封装好的API函数调取数据（不用ContextInfo），配合 Jupyter Notebook 灵活的功能，非常方便本平台用户进行高效的投资研究，但目前无法进行回测 |
| 使用区别 | 策略开发环境中存在主图的概念，模型可获取主图相关的数据，包括主图代码、主图行情、主图复权方式、主图K线序号、主图K线时间戳等，因此调用 API 函数 时，有部分参数是可以缺省，从主图获取 | 投资研究环境不存在主图的概念，在调用相关 API 函数时，必须注意，填写好股票代码、时间戳等，否则将无法获取正确的数据 |
| 函数数量 | 可调用平台上所有的 API 函数                                  | 目前投资研究环境仅提供策略开发环境 API 函数中获取数据相关的函数，后期将根据需求进一步丰富 |

**注(重要)：**

- 使用投资研究模块之前请务必通过菜单栏-【操作】-【数据管理】-【补充数据】面板，补充好相应的数据，可以补充的数据包括日线数据、分钟数据、分笔成交数据（tick数据）、财务数据等。**否则获取数据会失真。**
- 使用投资研究模块之前请务必通过菜单栏-【操作】-【数据管理】-【补充数据】面板，补充好相应的数据，可以补充的数据包括日线数据、分钟数据、分笔成交数据（tick数据）、财务数据等。**否则获取数据会失真。**
- 使用投资研究模块之前请务必通过菜单栏-【操作】-【数据管理】-【补充数据】面板，补充好相应的数据，可以补充的数据包括日线数据、分钟数据、分笔成交数据（tick数据）、财务数据等。**否则获取数据会失真。**

# 二、投资研究常用操作

- 使用 “Ctrl + Enter” 运行单个代码块

- 使用“ ? ”获取帮助

- 使用 Tab 键补全代码

**示例1：**

In [1]:
# 使用“ ? ”获取帮助示例，使用“Ctrl + Enter”运行；
import pandas as pd
pd.DataFrame?

**示例2：**

In [2]:
#使用 Tab 键补全函数名
get_

# 三、投资研究中可调用的 iQuant 接口函数

（1）获取最新流通股本 get_last_volume()

（2）获取指数成份股 get_sector()

（3）获取行业成份股 get_industry()

（4）获取板块成份股 get_stock_list_in_sector()

（5）获取某只股票在某指数中的绝对权重 get_weight_in_index()

（6）获取合约乘数 get_contract_multiplier()

（7）获取无风险利率 get_risk_free_rate()

（8）获取财务数据 get_financial_data()

（9）获取历史行情数据 get_market_data()

（10）获取除权除息日和复权因子 get_divid_factors()

（11）获取当前期货主力合约 get_main_contract()

（12）将毫秒时间转换成日期时间 timetag_to_date_time()

（13）获取指定个股 / 合约 / 指数的 K 线（交易日）列表 get_trading_dates()

（14）获取多因子数据 get_factor_data()

（15）获取指定期权列表 get_option_list()

（16）获取市场已退市合约 get_his_contract_list()

（17）根据代码获取合约详细信息 get_instrumentdetail()

（18）获取指定期权品种的详细信息 get_option_detail_data()

（19）获取指定期权品种的实时隐含波动率 get_option_iv()

（20）基于BS模型计算欧式期权理论价格 bsm_price()

（21）基于BS模型计算欧式期权隐含波动率 bsm_iv()

## （1）获取最新流通股本 get_last_volume()

**用法：**get_last_volume(stockcode)

**释义：** 获取最新流通股本

**参数：** 

- stockcode：str，合约代码，格式为 'stock.market' ，如 '600000.SH'

**返回：** float，单位：股

**示例：**

In [3]:
# 获取平安银行的流通股本
print('平安银行的流通股本（股）：', get_last_volume('000001.SZ'))

平安银行的流通股本（股）： 19405752680.0

## （2）获取指数成份股 get_sector()

**用法：** get_sector(sector[, date])

**释义：** 获取指数成份股

**参数：** 

- sector：str，必须是 'stock.market' 形式，如 '000300.SH' ，可取如沪深300（000300.SH）、中证500（000905.SH）、上证50（000016.SH）等指数的历史成份股
- date：str，日期，格式为yyyymmdd，如'20180508'，可缺省，目前只对沪深300（000300.SH）、中证500（000905.SH）、上证50（000016.SH）三个指数生效，如不填则默认取目前最新成份股

**返回：** list：内含成份股代码，代码形式为 'stockcode.market'，如 '000002.SZ'

**示例1：**

In [4]:
# 获取最新沪深300指数成分股
get_sector('000300.SH')

['000001.SZ',
 '000002.SZ',
 '000063.SZ',
 '000069.SZ',
 '000100.SZ',
 '000157.SZ',
 '000166.SZ',
 '000333.SZ',
 '000338.SZ',
 '000402.SZ',
 '000408.SZ',
 '000413.SZ',
 '000415.SZ',
 '000423.SZ',
 '000425.SZ',
 '000538.SZ',
 '000553.SZ',
 '000568.SZ',
 '000596.SZ',
 '000625.SZ',
 '000627.SZ',
 '000629.SZ',
 '000630.SZ',
 '000651.SZ',
 '000656.SZ',
 '000661.SZ',
 '000671.SZ',
 '000703.SZ',
 '000709.SZ',
 '000725.SZ',
 '000728.SZ',
 '000768.SZ',
 '000776.SZ',
 '000783.SZ',
 '000786.SZ',
 '000858.SZ',
 '000876.SZ',
 '000895.SZ',
 '000898.SZ',
 '000938.SZ',
 '000961.SZ',
 '000963.SZ',
 '001979.SZ',
 '002001.SZ',
 '002007.SZ',
 '002008.SZ',
 '002010.SZ',
 '002024.SZ',
 '002027.SZ',
 '002032.SZ',
 '002044.SZ',
 '002050.SZ',
 '002065.SZ',
 '002081.SZ',
 '002120.SZ',
 '002142.SZ',
 '002146.SZ',
 '002153.SZ',
 '002179.SZ',
 '002202.SZ',
 '002230.SZ',
 '002236.SZ',
 '002241.SZ',
 '002252.SZ',
 '002271.SZ',
 '002294.SZ',
 '002304.SZ',
 '002310.SZ',
 '002311.SZ',
 '002352.SZ',
 '002410.SZ',
 '002411.SZ',
 '002415.SZ',
 '002422.SZ',
 '002456.SZ',
 '002460.SZ',
 '002466.SZ',
 '002468.SZ',
 '002475.SZ',
 '002493.SZ',
 '002508.SZ',
 '002555.SZ',
 '002558.SZ',
 '002594.SZ',
 '002601.SZ',
 '002602.SZ',
 '002624.SZ',
 '002625.SZ',
 '002673.SZ',
 '002714.SZ',
 '002736.SZ',
 '002739.SZ',
 '002773.SZ',
 '002925.SZ',
 '002938.SZ',
 '002939.SZ',
 '002945.SZ',
 '300003.SZ',
 '300015.SZ',
 '300017.SZ',
 '300024.SZ',
 '300033.SZ',
 '300059.SZ',
 '300070.SZ',
 '300072.SZ',
 '300122.SZ',
 '300124.SZ',
 '300136.SZ',
 '300142.SZ',
 '300144.SZ',
 '300251.SZ',
 '300296.SZ',
 '300408.SZ',
 '300413.SZ',
 '300433.SZ',
 '300498.SZ',
 '600000.SH',
 '600004.SH',
 '600009.SH',
 '600010.SH',
 '600011.SH',
 '600015.SH',
 '600016.SH',
 '600018.SH',
 '600019.SH',
 '600023.SH',
 '600025.SH',
 '600027.SH',
 '600028.SH',
 '600029.SH',
 '600030.SH',
 '600031.SH',
 '600036.SH',
 '600038.SH',
 '600048.SH',
 '600050.SH',
 '600061.SH',
 '600066.SH',
 '600068.SH',
 '600085.SH',
 '600089.SH',
 '600100.SH',
 '600104.SH',
 '600109.SH',
 '600111.SH',
 '600115.SH',
 '600118.SH',
 '600153.SH',
 '600170.SH',
 '600176.SH',
 '600177.SH',
 '600188.SH',
 '600196.SH',
 '600208.SH',
 '600219.SH',
 '600221.SH',
 '600233.SH',
 '600271.SH',
 '600276.SH',
 '600297.SH',
 '600299.SH',
 '600309.SH',
 '600332.SH',
 '600339.SH',
 '600340.SH',
 '600346.SH',
 '600352.SH',
 '600362.SH',
 '600369.SH',
 '600372.SH',
 '600383.SH',
 '600390.SH',
 '600398.SH',
 '600406.SH',
 '600415.SH',
 '600436.SH',
 '600438.SH',
 '600482.SH',
 '600487.SH',
 '600489.SH',
 '600498.SH',
 '600516.SH',
 '600519.SH',
 '600522.SH',
 '600535.SH',
 '600547.SH',
 '600566.SH',
 '600570.SH',
 '600583.SH',
 '600585.SH',
 '600588.SH',
 '600606.SH',
 '600637.SH',
 '600660.SH',
 '600663.SH',
 '600674.SH',
 '600688.SH',
 '600690.SH',
 '600703.SH',
 '600704.SH',
 '600705.SH',
 '600733.SH',
 '600741.SH',
 '600760.SH',
 '600795.SH',
 '600809.SH',
 '600816.SH',
 '600837.SH',
 '600867.SH',
 '600886.SH',
 '600887.SH',
 '600893.SH',
 '600900.SH',
 '600919.SH',
 '600926.SH',
 '600958.SH',
 '600977.SH',
 '600998.SH',
 '600999.SH',
 '601006.SH',
 '601009.SH',
 '601012.SH',
 '601018.SH',
 '601021.SH',
 '601066.SH',
 '601088.SH',
 '601108.SH',
 '601111.SH',
 '601117.SH',
 '601138.SH',
 '601155.SH',
 '601162.SH',
 '601166.SH',
 '601169.SH',
 '601186.SH',
 '601198.SH',
 '601211.SH',
 '601212.SH',
 '601216.SH',
 '601225.SH',
 '601228.SH',
 '601229.SH',
 '601238.SH',
 '601288.SH',
 '601298.SH',
 '601318.SH',
 '601319.SH',
 '601328.SH',
 '601336.SH',
 '601360.SH',
 '601377.SH',
 '601390.SH',
 '601398.SH',
 '601555.SH',
 '601577.SH',
 '601600.SH',
 '601601.SH',
 '601607.SH',
 '601618.SH',
 '601628.SH',
 '601633.SH',
 '601668.SH',
 '601669.SH',
 '601688.SH',
 '601727.SH',
 '601766.SH',
 '601788.SH',
 '601800.SH',
 '601808.SH',
 '601818.SH',
 '601828.SH',
 '601838.SH',
 '601857.SH',
 '601877.SH',
 '601878.SH',
 '601881.SH',
 '601888.SH',
 '601898.SH',
 '601899.SH',
 '601901.SH',
 '601919.SH',
 '601933.SH',
 '601939.SH',
 '601985.SH',
 '601988.SH',
 '601989.SH',
 '601992.SH',
 '601997.SH',
 '601998.SH',
 '603019.SH',
 '603156.SH',
 '603160.SH',
 '603259.SH',
 '603260.SH',
 '603288.SH',
 '603799.SH',
 '603833.SH',
 '603858.SH',
 '603986.SH',
 '603993.SH']

**示例2：**

In [5]:
# 获取2013年10月10日沪深300指数成分股
get_sector('000300.SH', '20131010')

['000001.SZ',
 '000002.SZ',
 '000009.SZ',
 '000012.SZ',
 '000024.SZ',
 '000039.SZ',
 '000046.SZ',
 '000060.SZ',
 '000061.SZ',
 '000063.SZ',
 '000069.SZ',
 '000100.SZ',
 '000156.SZ',
 '000157.SZ',
 '000333.SZ',
 '000338.SZ',
 '000400.SZ',
 '000401.SZ',
 '000402.SZ',
 '000423.SZ',
 '000425.SZ',
 '000528.SZ',
 '000536.SZ',
 '000538.SZ',
 '000562.SZ',
 '000568.SZ',
 '000581.SZ',
 '000596.SZ',
 '000598.SZ',
 '000623.SZ',
 '000625.SZ',
 '000629.SZ',
 '000630.SZ',
 '000651.SZ',
 '000656.SZ',
 '000686.SZ',
 '000703.SZ',
 '000709.SZ',
 '000718.SZ',
 '000725.SZ',
 '000728.SZ',
 '000729.SZ',
 '000750.SZ',
 '000758.SZ',
 '000768.SZ',
 '000776.SZ',
 '000778.SZ',
 '000783.SZ',
 '000792.SZ',
 '000793.SZ',
 '000800.SZ',
 '000826.SZ',
 '000831.SZ',
 '000839.SZ',
 '000858.SZ',
 '000869.SZ',
 '000876.SZ',
 '000878.SZ',
 '000895.SZ',
 '000933.SZ',
 '000937.SZ',
 '000960.SZ',
 '000961.SZ',
 '000963.SZ',
 '000970.SZ',
 '000983.SZ',
 '000999.SZ',
 '002001.SZ',
 '002007.SZ',
 '002024.SZ',
 '002038.SZ',
 '002051.SZ',
 '002065.SZ',
 '002069.SZ',
 '002081.SZ',
 '002106.SZ',
 '002129.SZ',
 '002142.SZ',
 '002146.SZ',
 '002155.SZ',
 '002202.SZ',
 '002230.SZ',
 '002236.SZ',
 '002241.SZ',
 '002269.SZ',
 '002294.SZ',
 '002299.SZ',
 '002304.SZ',
 '002310.SZ',
 '002344.SZ',
 '002353.SZ',
 '002375.SZ',
 '002385.SZ',
 '002399.SZ',
 '002415.SZ',
 '002422.SZ',
 '002431.SZ',
 '002450.SZ',
 '002456.SZ',
 '002500.SZ',
 '002570.SZ',
 '002594.SZ',
 '002603.SZ',
 '002653.SZ',
 '002673.SZ',
 '600000.SH',
 '600008.SH',
 '600009.SH',
 '600010.SH',
 '600011.SH',
 '600015.SH',
 '600016.SH',
 '600018.SH',
 '600019.SH',
 '600027.SH',
 '600028.SH',
 '600029.SH',
 '600030.SH',
 '600031.SH',
 '600036.SH',
 '600048.SH',
 '600050.SH',
 '600058.SH',
 '600060.SH',
 '600062.SH',
 '600066.SH',
 '600068.SH',
 '600079.SH',
 '600085.SH',
 '600089.SH',
 '600096.SH',
 '600100.SH',
 '600104.SH',
 '600108.SH',
 '600109.SH',
 '600111.SH',
 '600115.SH',
 '600118.SH',
 '600123.SH',
 '600143.SH',
 '600150.SH',
 '600153.SH',
 '600157.SH',
 '600160.SH',
 '600166.SH',
 '600170.SH',
 '600177.SH',
 '600188.SH',
 '600196.SH',
 '600208.SH',
 '600216.SH',
 '600219.SH',
 '600221.SH',
 '600252.SH',
 '600256.SH',
 '600259.SH',
 '600266.SH',
 '600267.SH',
 '600271.SH',
 '600276.SH',
 '600309.SH',
 '600315.SH',
 '600316.SH',
 '600332.SH',
 '600340.SH',
 '600348.SH',
 '600352.SH',
 '600362.SH',
 '600369.SH',
 '600372.SH',
 '600376.SH',
 '600383.SH',
 '600395.SH',
 '600403.SH',
 '600406.SH',
 '600415.SH',
 '600436.SH',
 '600489.SH',
 '600497.SH',
 '600498.SH',
 '600516.SH',
 '600518.SH',
 '600519.SH',
 '600528.SH',
 '600535.SH',
 '600546.SH',
 '600547.SH',
 '600549.SH',
 '600582.SH',
 '600583.SH',
 '600585.SH',
 '600588.SH',
 '600597.SH',
 '600598.SH',
 '600600.SH',
 '600637.SH',
 '600642.SH',
 '600648.SH',
 '600649.SH',
 '600655.SH',
 '600660.SH',
 '600663.SH',
 '600664.SH',
 '600674.SH',
 '600688.SH',
 '600690.SH',
 '600694.SH',
 '600703.SH',
 '600705.SH',
 '600718.SH',
 '600739.SH',
 '600741.SH',
 '600783.SH',
 '600795.SH',
 '600804.SH',
 '600809.SH',
 '600811.SH',
 '600827.SH',
 '600832.SH',
 '600837.SH',
 '600839.SH',
 '600859.SH',
 '600863.SH',
 '600873.SH',
 '600875.SH',
 '600886.SH',
 '600887.SH',
 '600893.SH',
 '600895.SH',
 '600900.SH',
 '600970.SH',
 '600971.SH',
 '600997.SH',
 '600999.SH',
 '601001.SH',
 '601006.SH',
 '601009.SH',
 '601018.SH',
 '601088.SH',
 '601098.SH',
 '601099.SH',
 '601101.SH',
 '601106.SH',
 '601111.SH',
 '601117.SH',
 '601118.SH',
 '601139.SH',
 '601158.SH',
 '601166.SH',
 '601168.SH',
 '601169.SH',
 '601186.SH',
 '601231.SH',
 '601238.SH',
 '601258.SH',
 '601288.SH',
 '601299.SH',
 '601318.SH',
 '601328.SH',
 '601333.SH',
 '601336.SH',
 '601369.SH',
 '601377.SH',
 '601390.SH',
 '601398.SH',
 '601555.SH',
 '601600.SH',
 '601601.SH',
 '601607.SH',
 '601618.SH',
 '601628.SH',
 '601633.SH',
 '601666.SH',
 '601668.SH',
 '601669.SH',
 '601688.SH',
 '601699.SH',
 '601717.SH',
 '601766.SH',
 '601800.SH',
 '601808.SH',
 '601818.SH',
 '601857.SH',
 '601866.SH',
 '601888.SH',
 '601898.SH',
 '601899.SH',
 '601901.SH',
 '601918.SH',
 '601928.SH',
 '601933.SH',
 '601939.SH',
 '601958.SH',
 '601988.SH',
 '601989.SH',
 '601991.SH',
 '601992.SH',
 '601998.SH',
 '603000.SH',
 '603993.SH']

## （3）获取行业成份股 get_industry()

**用法：** get_industry(industry)

**释义：** 获取行业成份股，证监会行业，行业列表详见 Python Api 文档 - 5.2. 附录2 CSRC行业列表

**参数：** 

- industry：str，如 'CSRC采矿业'

**返回：** list：内含成份股代码，代码形式为 'stockcode.market'，如 '000002.SZ'

**示例：**

In [6]:
# 获取'CSRC采矿业'成分股
get_industry('CSRC采矿业')

['000426.SZ',
 '000506.SZ',
 '000552.SZ',
 '000571.SZ',
 '000603.SZ',
 '000629.SZ',
 '000655.SZ',
 '000688.SZ',
 '000693.SZ',
 '000697.SZ',
 '000758.SZ',
 '000762.SZ',
 '000780.SZ',
 '000937.SZ',
 '000968.SZ',
 '000975.SZ',
 '000983.SZ',
 '002128.SZ',
 '002155.SZ',
 '002207.SZ',
 '002554.SZ',
 '002629.SZ',
 '002683.SZ',
 '002828.SZ',
 '300084.SZ',
 '300157.SZ',
 '300164.SZ',
 '300191.SZ',
 '600028.SH',
 '600121.SH',
 '600123.SH',
 '600157.SH',
 '600188.SH',
 '600256.SH',
 '600259.SH',
 '600311.SH',
 '600338.SH',
 '600339.SH',
 '600348.SH',
 '600395.SH',
 '600397.SH',
 '600403.SH',
 '600489.SH',
 '600497.SH',
 '600508.SH',
 '600532.SH',
 '600547.SH',
 '600583.SH',
 '600711.SH',
 '600714.SH',
 '600758.SH',
 '600759.SH',
 '600766.SH',
 '600871.SH',
 '600971.SH',
 '600988.SH',
 '601001.SH',
 '601020.SH',
 '601069.SH',
 '601088.SH',
 '601101.SH',
 '601168.SH',
 '601225.SH',
 '601666.SH',
 '601699.SH',
 '601808.SH',
 '601857.SH',
 '601898.SH',
 '601899.SH',
 '601918.SH',
 '601958.SH',
 '601969.SH',
 '603505.SH',
 '603727.SH',
 '603979.SH',
 '603993.SH',
 '900948.SH']

## （4）获取板块成份股 get_stock_list_in_sector()

**用法：** get_stock_list_in_sector(sectorname[, date])

**释义：** 获取板块成份股，支持客户端左侧板块列表中任意的板块，包括自定义板块

**参数：** 

- sectorname：str，板块名，如'沪深300'，'中证500'、'上证50'、'我的自选'等
- date：str，日期，格式为yyyymmdd，如'20180508'，可缺省，目前只对沪深300、中证500、上证50三个板块生效，如不填则默认取目前最新成份股

**返回：** list：内含成份股代码，代码形式为 'stockcode.market'，如 '000002.SZ'

**示例1：**

In [7]:
# 获取客户端行情模块左侧板块中的'沪深300'板块成分股
get_stock_list_in_sector('沪深300')

['000001.SZ',
 '000002.SZ',
 '000063.SZ',
 '000069.SZ',
 '000100.SZ',
 '000157.SZ',
 '000166.SZ',
 '000333.SZ',
 '000338.SZ',
 '000402.SZ',
 '000408.SZ',
 '000413.SZ',
 '000415.SZ',
 '000423.SZ',
 '000425.SZ',
 '000538.SZ',
 '000553.SZ',
 '000568.SZ',
 '000596.SZ',
 '000625.SZ',
 '000627.SZ',
 '000629.SZ',
 '000630.SZ',
 '000651.SZ',
 '000656.SZ',
 '000661.SZ',
 '000671.SZ',
 '000703.SZ',
 '000709.SZ',
 '000725.SZ',
 '000728.SZ',
 '000768.SZ',
 '000776.SZ',
 '000783.SZ',
 '000786.SZ',
 '000858.SZ',
 '000876.SZ',
 '000895.SZ',
 '000898.SZ',
 '000938.SZ',
 '000961.SZ',
 '000963.SZ',
 '001979.SZ',
 '002001.SZ',
 '002007.SZ',
 '002008.SZ',
 '002010.SZ',
 '002024.SZ',
 '002027.SZ',
 '002032.SZ',
 '002044.SZ',
 '002050.SZ',
 '002065.SZ',
 '002081.SZ',
 '002120.SZ',
 '002142.SZ',
 '002146.SZ',
 '002153.SZ',
 '002179.SZ',
 '002202.SZ',
 '002230.SZ',
 '002236.SZ',
 '002241.SZ',
 '002252.SZ',
 '002271.SZ',
 '002294.SZ',
 '002304.SZ',
 '002310.SZ',
 '002311.SZ',
 '002352.SZ',
 '002410.SZ',
 '002411.SZ',
 '002415.SZ',
 '002422.SZ',
 '002456.SZ',
 '002460.SZ',
 '002466.SZ',
 '002468.SZ',
 '002475.SZ',
 '002493.SZ',
 '002508.SZ',
 '002555.SZ',
 '002558.SZ',
 '002594.SZ',
 '002601.SZ',
 '002602.SZ',
 '002624.SZ',
 '002625.SZ',
 '002673.SZ',
 '002714.SZ',
 '002736.SZ',
 '002739.SZ',
 '002773.SZ',
 '002925.SZ',
 '002938.SZ',
 '002939.SZ',
 '002945.SZ',
 '300003.SZ',
 '300015.SZ',
 '300017.SZ',
 '300024.SZ',
 '300033.SZ',
 '300059.SZ',
 '300070.SZ',
 '300072.SZ',
 '300122.SZ',
 '300124.SZ',
 '300136.SZ',
 '300142.SZ',
 '300144.SZ',
 '300251.SZ',
 '300296.SZ',
 '300408.SZ',
 '300413.SZ',
 '300433.SZ',
 '300498.SZ',
 '600000.SH',
 '600004.SH',
 '600009.SH',
 '600010.SH',
 '600011.SH',
 '600015.SH',
 '600016.SH',
 '600018.SH',
 '600019.SH',
 '600023.SH',
 '600025.SH',
 '600027.SH',
 '600028.SH',
 '600029.SH',
 '600030.SH',
 '600031.SH',
 '600036.SH',
 '600038.SH',
 '600048.SH',
 '600050.SH',
 '600061.SH',
 '600066.SH',
 '600068.SH',
 '600085.SH',
 '600089.SH',
 '600100.SH',
 '600104.SH',
 '600109.SH',
 '600111.SH',
 '600115.SH',
 '600118.SH',
 '600153.SH',
 '600170.SH',
 '600176.SH',
 '600177.SH',
 '600188.SH',
 '600196.SH',
 '600208.SH',
 '600219.SH',
 '600221.SH',
 '600233.SH',
 '600271.SH',
 '600276.SH',
 '600297.SH',
 '600299.SH',
 '600309.SH',
 '600332.SH',
 '600339.SH',
 '600340.SH',
 '600346.SH',
 '600352.SH',
 '600362.SH',
 '600369.SH',
 '600372.SH',
 '600383.SH',
 '600390.SH',
 '600398.SH',
 '600406.SH',
 '600415.SH',
 '600436.SH',
 '600438.SH',
 '600482.SH',
 '600487.SH',
 '600489.SH',
 '600498.SH',
 '600516.SH',
 '600519.SH',
 '600522.SH',
 '600535.SH',
 '600547.SH',
 '600566.SH',
 '600570.SH',
 '600583.SH',
 '600585.SH',
 '600588.SH',
 '600606.SH',
 '600637.SH',
 '600660.SH',
 '600663.SH',
 '600674.SH',
 '600688.SH',
 '600690.SH',
 '600703.SH',
 '600704.SH',
 '600705.SH',
 '600733.SH',
 '600741.SH',
 '600760.SH',
 '600795.SH',
 '600809.SH',
 '600816.SH',
 '600837.SH',
 '600867.SH',
 '600886.SH',
 '600887.SH',
 '600893.SH',
 '600900.SH',
 '600919.SH',
 '600926.SH',
 '600958.SH',
 '600977.SH',
 '600998.SH',
 '600999.SH',
 '601006.SH',
 '601009.SH',
 '601012.SH',
 '601018.SH',
 '601021.SH',
 '601066.SH',
 '601088.SH',
 '601108.SH',
 '601111.SH',
 '601117.SH',
 '601138.SH',
 '601155.SH',
 '601162.SH',
 '601166.SH',
 '601169.SH',
 '601186.SH',
 '601198.SH',
 '601211.SH',
 '601212.SH',
 '601216.SH',
 '601225.SH',
 '601228.SH',
 '601229.SH',
 '601238.SH',
 '601288.SH',
 '601298.SH',
 '601318.SH',
 '601319.SH',
 '601328.SH',
 '601336.SH',
 '601360.SH',
 '601377.SH',
 '601390.SH',
 '601398.SH',
 '601555.SH',
 '601577.SH',
 '601600.SH',
 '601601.SH',
 '601607.SH',
 '601618.SH',
 '601628.SH',
 '601633.SH',
 '601668.SH',
 '601669.SH',
 '601688.SH',
 '601727.SH',
 '601766.SH',
 '601788.SH',
 '601800.SH',
 '601808.SH',
 '601818.SH',
 '601828.SH',
 '601838.SH',
 '601857.SH',
 '601877.SH',
 '601878.SH',
 '601881.SH',
 '601888.SH',
 '601898.SH',
 '601899.SH',
 '601901.SH',
 '601919.SH',
 '601933.SH',
 '601939.SH',
 '601985.SH',
 '601988.SH',
 '601989.SH',
 '601992.SH',
 '601997.SH',
 '601998.SH',
 '603019.SH',
 '603156.SH',
 '603160.SH',
 '603259.SH',
 '603260.SH',
 '603288.SH',
 '603799.SH',
 '603833.SH',
 '603858.SH',
 '603986.SH',
 '603993.SH']

**示例2：**

In [8]:
# 获取2013年10月10日沪深300板块成分股
get_stock_list_in_sector('沪深300', '20131010')

['000001.SZ',
 '000002.SZ',
 '000009.SZ',
 '000012.SZ',
 '000024.SZ',
 '000039.SZ',
 '000046.SZ',
 '000060.SZ',
 '000061.SZ',
 '000063.SZ',
 '000069.SZ',
 '000100.SZ',
 '000156.SZ',
 '000157.SZ',
 '000333.SZ',
 '000338.SZ',
 '000400.SZ',
 '000401.SZ',
 '000402.SZ',
 '000423.SZ',
 '000425.SZ',
 '000528.SZ',
 '000536.SZ',
 '000538.SZ',
 '000562.SZ',
 '000568.SZ',
 '000581.SZ',
 '000596.SZ',
 '000598.SZ',
 '000623.SZ',
 '000625.SZ',
 '000629.SZ',
 '000630.SZ',
 '000651.SZ',
 '000656.SZ',
 '000686.SZ',
 '000703.SZ',
 '000709.SZ',
 '000718.SZ',
 '000725.SZ',
 '000728.SZ',
 '000729.SZ',
 '000750.SZ',
 '000758.SZ',
 '000768.SZ',
 '000776.SZ',
 '000778.SZ',
 '000783.SZ',
 '000792.SZ',
 '000793.SZ',
 '000800.SZ',
 '000826.SZ',
 '000831.SZ',
 '000839.SZ',
 '000858.SZ',
 '000869.SZ',
 '000876.SZ',
 '000878.SZ',
 '000895.SZ',
 '000933.SZ',
 '000937.SZ',
 '000960.SZ',
 '000961.SZ',
 '000963.SZ',
 '000970.SZ',
 '000983.SZ',
 '000999.SZ',
 '002001.SZ',
 '002007.SZ',
 '002024.SZ',
 '002038.SZ',
 '002051.SZ',
 '002065.SZ',
 '002069.SZ',
 '002081.SZ',
 '002106.SZ',
 '002129.SZ',
 '002142.SZ',
 '002146.SZ',
 '002155.SZ',
 '002202.SZ',
 '002230.SZ',
 '002236.SZ',
 '002241.SZ',
 '002269.SZ',
 '002294.SZ',
 '002299.SZ',
 '002304.SZ',
 '002310.SZ',
 '002344.SZ',
 '002353.SZ',
 '002375.SZ',
 '002385.SZ',
 '002399.SZ',
 '002415.SZ',
 '002422.SZ',
 '002431.SZ',
 '002450.SZ',
 '002456.SZ',
 '002500.SZ',
 '002570.SZ',
 '002594.SZ',
 '002603.SZ',
 '002653.SZ',
 '002673.SZ',
 '600000.SH',
 '600008.SH',
 '600009.SH',
 '600010.SH',
 '600011.SH',
 '600015.SH',
 '600016.SH',
 '600018.SH',
 '600019.SH',
 '600027.SH',
 '600028.SH',
 '600029.SH',
 '600030.SH',
 '600031.SH',
 '600036.SH',
 '600048.SH',
 '600050.SH',
 '600058.SH',
 '600060.SH',
 '600062.SH',
 '600066.SH',
 '600068.SH',
 '600079.SH',
 '600085.SH',
 '600089.SH',
 '600096.SH',
 '600100.SH',
 '600104.SH',
 '600108.SH',
 '600109.SH',
 '600111.SH',
 '600115.SH',
 '600118.SH',
 '600123.SH',
 '600143.SH',
 '600150.SH',
 '600153.SH',
 '600157.SH',
 '600160.SH',
 '600166.SH',
 '600170.SH',
 '600177.SH',
 '600188.SH',
 '600196.SH',
 '600208.SH',
 '600216.SH',
 '600219.SH',
 '600221.SH',
 '600252.SH',
 '600256.SH',
 '600259.SH',
 '600266.SH',
 '600267.SH',
 '600271.SH',
 '600276.SH',
 '600309.SH',
 '600315.SH',
 '600316.SH',
 '600332.SH',
 '600340.SH',
 '600348.SH',
 '600352.SH',
 '600362.SH',
 '600369.SH',
 '600372.SH',
 '600376.SH',
 '600383.SH',
 '600395.SH',
 '600403.SH',
 '600406.SH',
 '600415.SH',
 '600436.SH',
 '600489.SH',
 '600497.SH',
 '600498.SH',
 '600516.SH',
 '600518.SH',
 '600519.SH',
 '600528.SH',
 '600535.SH',
 '600546.SH',
 '600547.SH',
 '600549.SH',
 '600582.SH',
 '600583.SH',
 '600585.SH',
 '600588.SH',
 '600597.SH',
 '600598.SH',
 '600600.SH',
 '600637.SH',
 '600642.SH',
 '600648.SH',
 '600649.SH',
 '600655.SH',
 '600660.SH',
 '600663.SH',
 '600664.SH',
 '600674.SH',
 '600688.SH',
 '600690.SH',
 '600694.SH',
 '600703.SH',
 '600705.SH',
 '600718.SH',
 '600739.SH',
 '600741.SH',
 '600783.SH',
 '600795.SH',
 '600804.SH',
 '600809.SH',
 '600811.SH',
 '600827.SH',
 '600832.SH',
 '600837.SH',
 '600839.SH',
 '600859.SH',
 '600863.SH',
 '600873.SH',
 '600875.SH',
 '600886.SH',
 '600887.SH',
 '600893.SH',
 '600895.SH',
 '600900.SH',
 '600970.SH',
 '600971.SH',
 '600997.SH',
 '600999.SH',
 '601001.SH',
 '601006.SH',
 '601009.SH',
 '601018.SH',
 '601088.SH',
 '601098.SH',
 '601099.SH',
 '601101.SH',
 '601106.SH',
 '601111.SH',
 '601117.SH',
 '601118.SH',
 '601139.SH',
 '601158.SH',
 '601166.SH',
 '601168.SH',
 '601169.SH',
 '601186.SH',
 '601231.SH',
 '601238.SH',
 '601258.SH',
 '601288.SH',
 '601299.SH',
 '601318.SH',
 '601328.SH',
 '601333.SH',
 '601336.SH',
 '601369.SH',
 '601377.SH',
 '601390.SH',
 '601398.SH',
 '601555.SH',
 '601600.SH',
 '601601.SH',
 '601607.SH',
 '601618.SH',
 '601628.SH',
 '601633.SH',
 '601666.SH',
 '601668.SH',
 '601669.SH',
 '601688.SH',
 '601699.SH',
 '601717.SH',
 '601766.SH',
 '601800.SH',
 '601808.SH',
 '601818.SH',
 '601857.SH',
 '601866.SH',
 '601888.SH',
 '601898.SH',
 '601899.SH',
 '601901.SH',
 '601918.SH',
 '601928.SH',
 '601933.SH',
 '601939.SH',
 '601958.SH',
 '601988.SH',
 '601989.SH',
 '601991.SH',
 '601992.SH',
 '601998.SH',
 '603000.SH',
 '603993.SH']

## （5）获取某只股票在某指数中的绝对权重 get_weight_in_index()

**用法：** get_weight_in_index(indexcode, stockcode)

**释义：** 获取某只股票在某指数中的绝对权重

**参数：** 

- indexcode：str，指数代码，形式为 'stockcode.market'，如 '000300.SH'   
- stockcode：str，股票代码，形式为 'stockcode.market'，如 '600004.SH'

**返回：** float：返回的数值单位是 %，如返回 1.6134，则表示权重是 1.6134%

**示例：**

In [9]:
# 获取平安银行'000001.SZ'在沪深300指数中的绝对权重
print('平安银行在沪深300指数中的绝对权重：', get_weight_in_index('000300.SH', '000001.SZ'))

平安银行在沪深300指数中的绝对权重： 0.9812

## （6）获取合约乘数 get_contract_multiplier()

**用法：** get_contract_multiplier(contractcode)

**释义：** 获取合约乘数

**参数：** 

- contractcode：str，合约代码，形式为 'code.market'，如 'IF00.IF'

**返回：** int

**示例：**

In [10]:
#获取沪深300股指期货合约乘数
print('沪深300股指期货合约乘数:', get_contract_multiplier('IF00.IF'))

沪深300股指期货合约乘数: 300

## （7）获取无风险利率 get_risk_free_rate()

**用法：** get_risk_free_rate(date)

**释义：** 获取无风险利率，用十年期国债收益率 CGB10Y 作无风险利率

**参数：**

- date：str，日期，格式为yyyymmdd，如'20180508'

**返回：** float

**示例：**

In [11]:
# 获取2019年10月10日的无风险利率
print('2019年10月10日无风险利率：', get_risk_free_rate('20191010'))

2019年10月10日无风险利率： 3.5

## （8） 获取财务数据 get_financial_data()

**用法：** get_financial_data(field_list, stock_list, start_date, end_date[, report_type = 'announce_time'])

**释义：** 获取财务数据

**参数：** 

- field_list：list，字段列表，如 ['CAPITALSTRUCTURE.total_capital', 'ASHAREINCOME.net_profit_incl_min_int_inc']   （例子中取了股本结构中的总股本，与利润表中的净利润），更多支持字段参见 Python Api 文档 - 4.3. 财务数据字段对照表)
- stock_list：list，股票列表，如 ['600000.SH', '000001.SZ']
- start_date：str，开始时间，如 '20171209' 
- end_date：str，结束时间，如 '20171212'
- report_type：str，时间类型，可缺省，默认是按照数据的公告期为区分取数据，设置为 'report_time' 为按照报告期取数据。可选值：'announce_time'，'report_time'

**返回：** 

> 函数根据 stock_list 代码列表，startDate，endDate 时间范围的大小范围不同的数据类型：
>
> （1）代码列表 1，时间范围为 1，返回：pandas.Series，index = 字段
>
> （2）代码列表 1，时间范围为 n，返回：pandas.DataFrame，index = 时间，columns = 字段
>
> （3）代码列表 n，时间范围为 1，返回：pandas.DataFrame，index = 代码，columns = 字段
>
> （4）代码列表 n，时间范围为 n，返回：pandas.Panel，items = 代码，major_axis = 时间，minor_axis = 字段
>
> 选择按照公告期取数和按照报告期取数的区别：若某公司当年4月26日发布上年度年报，如果选择按照公告期取数，则当年4月26日之后至下个财报发布日期之间的数据都是上年度年报的财务数据，如果选择按照报告期取数，则上年度第4季度（上年度10月1日 - 12月31日）的数据就是上年度报告期的数据。

*注：必须安装pandas

**示例1：** 

**代码列表 1，时间范围为 1，返回：pandas.Series，index = 字段**

In [12]:
# 获取平安银行股本结构中的总股本
field_list = ['CAPITALSTRUCTURE.total_capital']
stock_list = ['000001.SZ']
start_date = '20171211'
end_date = '20171211'

# 获取20171211 - 20171215时间段平安银行和浦发银行的总股本
data = get_financial_data(field_list, stock_list, start_date, end_date)

# 打印数据类型
print('代码列表为1、时间范围为1，返回的数据类型：\n', type(data))

#输出总股本
print('\n数据内容：')
data

代码列表为1、时间范围为1，返回的数据类型：
 <class 'pandas.core.series.Series'>

数据内容：

total_capital    1.717041e+10
dtype: float64

**示例2：** 

**代码列表 1，时间范围为 n，返回：pandas.DataFrame，index = 时间，columns = 字段**

In [13]:
# 获取平安银行股本结构中的总股本
field_list = ['CAPITALSTRUCTURE.total_capital']
stock_list = ['000001.SZ']
start_date = '20171211'
end_date = '20171215'

# 获取20171211 - 20171215时间段平安银行和浦发银行的总股本
data = get_financial_data(field_list, stock_list, start_date, end_date)

# 打印数据类型
print('代码列表为1、时间范围为n，返回的数据类型：\n', type(data))

#输出总股本
print('\n数据内容：')
data

代码列表为1、时间范围为n，返回的数据类型：
 <class 'pandas.core.frame.DataFrame'>

数据内容：

          total_capital
20171211   1.717041e+10
20171212   1.717041e+10
20171213   1.717041e+10
20171214   1.717041e+10
20171215   1.717041e+10

**示例3：** 

**代码列表 n，时间范围为 1，返回：pandas.DataFrame，index = 代码，columns = 字段**

In [14]:
# 获取平安银行股本结构中的总股本，与利润表中的净利润
field_list = ['CAPITALSTRUCTURE.total_capital', 'ASHAREINCOME.net_profit_incl_min_int_inc']
stock_list = ['000001.SZ', '600000.SH']
start_date = '20171211'
end_date = '20171211'

# 获取20171211 - 20171215时间段平安银行的总股本及利润表的净利润
data = get_financial_data(field_list, stock_list, start_date, end_date)

# 打印数据类型
print('代码列表为n、时间范围为1，返回的数据类型：\n', type(data))

#输出总股本
print('\n数据内容：')
data

代码列表为n、时间范围为1，返回的数据类型：
 <class 'pandas.core.frame.DataFrame'>

数据内容：

           total_capital  net_profit_incl_min_int_inc
000001.SZ   1.717041e+10                 1.871900e+10
600000.SH   2.935208e+10                 4.113800e+10

**示例4：** 

**代码列表 n，时间范围为 n，返回：pandas.Panel，items = 代码，major_axis = 时间，minor_axis = 字段**

In [15]:
# 获取平安银行和浦发银行股本结构中的总股本，与利润表中的净利润
field_list = ['CAPITALSTRUCTURE.total_capital', 'ASHAREINCOME.net_profit_incl_min_int_inc']
stock_list = ['000001.SZ', '600000.SH']
start_date = '20171211'
end_date = '20171215'

# 获取20171211 - 20171215时间段平安银行和浦发银行的总股本及利润表的净利润
data = get_financial_data(field_list, stock_list, start_date, end_date)

# 打印数据类型
print('代码列表为n、时间范围为n，返回的数据类型：\n', data)

# 打印数据内容，panel 转成 dataframe 显示
print('\n数据内容：\n')
data.to_frame()

代码列表为n、时间范围为n，返回的数据类型：
 <class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 5 (major_axis) x 2 (minor_axis)
Items axis: 000001.SZ to 600000.SH
Major_axis axis: 20171211 to 20171215
Minor_axis axis: total_capital to net_profit_incl_min_int_inc

数据内容：

                                         000001.SZ     600000.SH
major    minor
20171211 total_capital                1.717041e+10  2.935208e+10
         net_profit_incl_min_int_inc  1.871900e+10  4.113800e+10
20171212 total_capital                1.717041e+10  2.935208e+10
         net_profit_incl_min_int_inc  1.871900e+10  4.113800e+10
20171213 total_capital                1.717041e+10  2.935208e+10
         net_profit_incl_min_int_inc  1.871900e+10  4.113800e+10
20171214 total_capital                1.717041e+10  2.935208e+10
         net_profit_incl_min_int_inc  1.871900e+10  4.113800e+10
20171215 total_capital                1.717041e+10  2.935208e+10
         net_profit_incl_min_int_inc  1.871900e+10  4.113800e+10

## （9）获取历史行情数据 get_market_data()

**用法：** get_market_data(fields, stock_code[, start_time = '', end_time = '' , period = '1d', dividend_type = 'none', count = -1])

**释义：** 获取历史行情数据

**参数：** 

- fields：list，字段列表：

  > 'open'：开
  >
  > 'high'：高 
  >
  > 'low'：低
  >
  > 'close'：收
  >
  > 'volume'：成交量
  >
  > 'amount'：成交额
  >
  > 'settle'：结算价
  >
  > 'quoter'：分笔数据（包括历史）

  - 'quoter'分笔数据结构：dict

    {

    > lastPrice：最新价
    >
    >
    > amount：成交额
    >
    > volume：成交量
    >
    > pvolumn：前成交量
    >
    > openInt：持仓量
    >
    > stockStatus：股票状态
    >
    > lastSettlementPrice：最新结算价
    >
    > open：开盘价
    >
    > high：最高价 
    >
    > low：最低价
    >
    > settlementPrice：结算价
    >
    > lastClose：收盘价
    >
    > askPrice：列表，卖价五档 
    >
    > bidPrice：列表，买价五档
    >
    > askVol：列表，卖量五档
    >
    > bidVol；列表，买量五档

     }   

- stock_code ：list，合约代码列表，合约格式 code.market，如[ '000001.SZ', '600000.SH'] 

- start_time：str，可选参数，开始时间，格式 '20171209' 或 '20171209010101'   

- end_time：str，可选参数，结束时间，格式 '20171209' 或 '20171209010101' 

- period：str，可选参数，周期类型：

  > 'tick'：分笔线
  >
  > '1d'：日线
  >
  > '1m'：1分钟线
  >
  > '3m'：3分钟线
  >
  > '5m'：5分钟线
  >
  > '15m'：15分钟线  
  >
  > '30m'：30分钟线
  >
  > '1h'：小时线
  >
  > '1w'：周线
  >
  > '1mon'：月线
  >
  > '1q'：季线
  >
  > '1hy'：半年线
  >
  > '1y'：年线

- dividend_type：可选参数，缺省值为 'none'，除复权，可选值：

  > 'none'：不复权
  >
  > 'front'：向前复权
  >
  > 'back'：向后复权
  >
  > 'front_ratio'：等比向前复权
  >
  > 'back_ratio'：等比向后复权   

- count：int，可选参数，缺省值为 -1。

  count 和开始时间、结束时间同时设置的效果如下表： 

| count 取值 | 时间设置是否生效 | 开始时间和结束时间设置效果                              |
| :--------- | :--------------- | :------------------------------------------------------ |
| count >= 0 | **结束时间生效** | 从结束时间往回取多少个周期的值，取值数量完全取决于count |
| count = -1 | **生效**         | 同时设置开始时间和结束时间，在所设置的时间段内取值      |
| count = -1 | **生效**         | 开始时间结束时间都不设置，取当前最新bar的值             |
| count = -1 | **生效**         | 只设置开始时间，取所设开始时间到当前时间的值            |
| count = -1 | **生效**         | 只设置结束时间，取股票上市第一根 bar 到所设结束时间的值 |

*注：特别的，默认参数需带上参数名方可生效，调用方式与 Python 别无二致

**返回：** 

**不同的参数（代码、字段、时间），返回的数据结构不同，示例中说明了返回的不同的数据结构的类型。**

> 代码：指股票代码
>
> 字段：即 fields 里的字段
>
> 时间：即为函数中所设置的时间，主要由 count、start_time、end_time 决定

**示例1：** 

**1只股票代码、1个字段、count缺省（缺省值为-1，代表最新时间点）时返回的数据类型：相应字段的值**

In [16]:
# 获取平安银行最新的收盘价
data = get_market_data(
    fields = ['close'], 
    stock_code = ['000001.SZ'], 
    period = '1d', 
    dividend_type = 'front')

# 打印数据类型
print('1只股票代码、1个字段、count缺省（缺省值为-1）时返回的数据类型：\n', type(data))

# 显示数据
print('\n数据内容：')
data

1只股票代码、1个字段、count缺省（缺省值为-1）时返回的数据类型：
 <class 'float'>

数据内容：

12.59

**示例2：** 

**1只股票代码、n个字段、count缺省（缺省值为-1，代表最新时间点）时返回的数据类型：pandas.Series（pandas 一维数组）类型**

In [17]:
# 获取平安银行最新的开盘价、收盘价
data = get_market_data(
    fields = ['open', 'high', 'low', 'close', 'volume', 'amount'], 
    stock_code = ['000001.SZ'], 
    period = '1d', 
    dividend_type = 'front')

# 打印数据类型
print('1只股票代码、n个字段、count缺省（缺省值为-1）时返回的数据类型：\n', type(data))

# 显示数据
print('\n数据内容：')
data

1只股票代码、n个字段、count缺省（缺省值为-1）时返回的数据类型：
 <class 'pandas.core.series.Series'>

数据内容：

amount    5.620081e+08
close     1.259000e+01
high      1.271000e+01
low       1.247000e+01
open      1.267000e+01
volume    4.462140e+05
dtype: float64

**示例3：** 

**1只股票代码、n个字段、count>0 时返回的数据类型：pandas.DataFrame（pandas 二维表格型数据结构）类型**

In [18]:
# 获取平安银行最近3个交易日的开、高、低、收、成交量，成交额
data = get_market_data(
    fields = ['open', 'high', 'low', 'close', 'volume', 'amount'], 
    stock_code = ['000001.SZ'], 
    period = '1d', 
    dividend_type = 'front', 
    count = 3)

# 打印数据类型
print('1只股票代码、n个字段、count>0 时返回的数据类型：\n', type(data))

# 显示数据
print('\n数据内容：')
data

1只股票代码、n个字段、count>0 时返回的数据类型：
 <class 'pandas.core.frame.DataFrame'>

数据内容：

           open   high    low  close    volume       amount
20200409  12.88  12.89  12.72  12.74  408553.0  522027904.0
20200410  12.76  12.98  12.65  12.79  666674.0  853689920.0
20200413  12.67  12.71  12.47  12.59  446214.0  562008064.0

**示例4：** 

**1只股票代码、n个字段、使用时间段取值时返回的数据类型：pandas.DataFrame（pandas 二维表格型数据结构）类型**

In [19]:
# 获取平安银行在20190513 - 20190517时间段的开、高、低、收、成交量，成交额
data = get_market_data(
    fields = ['open', 'high', 'low', 'close', 'volume', 'amount'], 
    stock_code = ['000001.SZ'], 
    start_time = '20190513', 
    end_time = '20190517' , 
    period = '1d', 
    dividend_type = 'front')

# 打印数据类型
print('1只股票代码、n个字段、使用时间段取值时返回的数据类型：\n', type(data))

# 显示数据
print('\n数据内容：')
data

1只股票代码、n个字段、使用时间段取值时返回的数据类型：
 <class 'pandas.core.frame.DataFrame'>

数据内容：

            open    high     low   close     volume        amount
20190513  12.185  12.395  12.085  12.155   741917.0  9.162137e+08
20190514  12.055  12.605  12.015  12.345  1182598.0  1.477008e+09
20190515  12.435  12.965  12.425  12.775  1103988.0  1.417050e+09
20190516  12.785  12.845  12.635  12.705   634901.0  8.167409e+08
20190517  12.775  12.785  12.215  12.295   965000.0  1.208570e+09

**示例5：** 

**n只股票代码、n个字段、count>0 时返回的数据类型：pandas.Panel（pandas 三维数组结构）类型**

In [20]:
# 获取平安银行最近3个交易日的开、高、低、收、成交量，成交额
data = get_market_data(
    fields = ['open', 'high', 'low', 'close', 'volume', 'amount'], 
    stock_code = ['000001.SZ', '600000.SH'],
    period = '1d', 
    dividend_type = 'front', 
    count = 3)

# 打印数据类型
print('n只股票代码、n个字段、count>0 时返回的数据类型：\n', data)

# 打印数据内容，panel 转成 dataframe 显示
print('\n数据内容：\n')
data.to_frame()

n只股票代码、n个字段、count>0 时返回的数据类型：
 <class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 3 (major_axis) x 6 (minor_axis)
Items axis: 000001.SZ to 600000.SH
Major_axis axis: 20200409 to 20200413
Minor_axis axis: open to amount

数据内容：

                    000001.SZ     600000.SH
major    minor
20200409 open    1.288000e+01  1.026000e+01
         high    1.289000e+01  1.029000e+01
         low     1.272000e+01  1.018000e+01
         close   1.274000e+01  1.020000e+01
         volume  4.085530e+05  1.356950e+05
         amount  5.220279e+08  1.388810e+08
20200410 open    1.276000e+01  1.022000e+01
         high    1.298000e+01  1.024000e+01
         low     1.265000e+01  1.015000e+01
         close   1.279000e+01  1.021000e+01
         volume  6.666740e+05  1.662550e+05
         amount  8.536899e+08  1.696259e+08
20200413 open    1.267000e+01  1.015000e+01
         high    1.271000e+01  1.022000e+01
         low     1.247000e+01  1.010000e+01
         close   1.259000e+01  1.011000e+01
         volume  4.462140e+05  1.196690e+05
         amount  5.620081e+08  1.213155e+08

**示例6：** 

**n只股票代码、n个字段、使用时间段取值时返回的数据类型：pandas.Panel（pandas 三维数组结构）类型**

In [21]:
# 获取平安银行和浦发银行在20190513 - 20190524时间段的开、高、低、收、成交量，成交额
data = get_market_data(
    fields = ['open', 'high', 'low', 'close', 'volume', 'amount'], 
    stock_code = ['000001.SZ', '600000.SH'], 
    start_time = '20190513', 
    end_time = '20190524' , 
    period = '1d', 
    dividend_type = 'front')

# 打印数据类型
print('n只股票代码、n个字段、使用时间段取值时返回的数据类型：\n', data)

# 打印数据内容，panel 转成 dataframe 显示
print('\n数据内容：\n')
data.to_frame()

n只股票代码、n个字段、使用时间段取值时返回的数据类型：
 <class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 10 (major_axis) x 6 (minor_axis)
Items axis: 000001.SZ to 600000.SH
Major_axis axis: 20190513 to 20190524
Minor_axis axis: open to amount

数据内容：

                    000001.SZ     600000.SH
major    minor
20190513 open    1.218500e+01  1.085000e+01
         high    1.239500e+01  1.105000e+01
         low     1.208500e+01  1.080000e+01
         close   1.215500e+01  1.096000e+01
         volume  7.419170e+05  4.028490e+05
         amount  9.162137e+08  4.556431e+08
20190514 open    1.205500e+01  1.083000e+01
         high    1.260500e+01  1.109000e+01
         low     1.201500e+01  1.082000e+01
         close   1.234500e+01  1.086000e+01
         volume  1.182598e+06  4.188900e+05
         amount  1.477008e+09  4.731515e+08
20190515 open    1.243500e+01  1.093000e+01
         high    1.296500e+01  1.107000e+01
         low     1.242500e+01  1.088000e+01
         close   1.277500e+01  1.097000e+01
         volume  1.103988e+06  3.440440e+05
         amount  1.417050e+09  3.895334e+08
20190516 open    1.278500e+01  1.093000e+01
         high    1.284500e+01  1.101000e+01
         low     1.263500e+01  1.087000e+01
         close   1.270500e+01  1.095000e+01
         volume  6.349010e+05  3.414170e+05
         amount  8.167409e+08  3.850152e+08
20190517 open    1.277500e+01  1.097000e+01
         high    1.278500e+01  1.100000e+01
         low     1.221500e+01  1.085000e+01
         close   1.229500e+01  1.089000e+01
         volume  9.650000e+05  3.839980e+05
         amount  1.208570e+09  4.331080e+08
20190520 open    1.220500e+01  1.093000e+01
         high    1.239500e+01  1.109000e+01
         low     1.210500e+01  1.090000e+01
         close   1.223500e+01  1.099000e+01
         volume  7.864350e+05  3.490440e+05
         amount  9.712225e+08  3.964484e+08
20190521 open    1.225500e+01  1.098000e+01
         high    1.258500e+01  1.110000e+01
         low     1.221500e+01  1.096000e+01
         close   1.241500e+01  1.097000e+01
         volume  7.312100e+05  3.297580e+05
         amount  9.191912e+08  3.749726e+08
20190522 open    1.242500e+01  1.097000e+01
         high    1.242500e+01  1.099000e+01
         low     1.217500e+01  1.077000e+01
         close   1.225500e+01  1.081000e+01
         volume  5.062300e+05  4.000030e+05
         amount  6.284374e+08  4.478288e+08
20190523 open    1.209500e+01  1.077000e+01
         high    1.227500e+01  1.080000e+01
         low     1.199500e+01  1.060000e+01
         close   1.214500e+01  1.075000e+01
         volume  6.668550e+05  3.631260e+05
         amount  8.178506e+08  4.017092e+08
20190524 open    1.220500e+01  1.082000e+01
         high    1.230500e+01  1.087000e+01
         low     1.216500e+01  1.065000e+01
         close   1.220500e+01  1.076000e+01
         volume  4.955260e+05  2.416020e+05
         amount  6.131062e+08  2.693124e+08

**示例7（获取tick数据）：** 

**1只股票代码、count缺省（缺省值为-1，代表最新时间点）时获取的tick数据类型：dict（Python 字典）类型**

In [22]:
# 获取平安最新tick数据
data = get_market_data(fields = ['quoter'],
                stock_code = ['000001.SZ'],
                period = 'tick')

# 打印数据类型
print('1只股票代码、count缺省（缺省值为-1）时获取的tick数据类型：\n', type(data))

# 显示数据
print('\n数据内容：')
data

1只股票代码、count缺省（缺省值为-1）时获取的tick数据类型：
 <class 'dict'>

数据内容：

{'amount': 562008064.0,
 'high': 12.71,
 'lastClose': 12.79,
 'lastPrice': 12.59,
 'lastSettlementPrice': 0.0,
 'low': 12.47,
 'open': 12.67,
 'openInt': 0.0,
 'pvolume': 44621440.0,
 'settlementPrice': 0.0,
 'stockStatus': 1.0,
 'volume': 446214.0,
 'askPrice': [12.6, 12.61, 12.62, 12.63, 12.64],
 'askVol': [1963.0, 628.0, 757.0, 1277.0, 947.0],
 'bidPrice': [12.59, 12.58, 12.57, 12.56, 12.55],
 'bidVol': [594.0, 2037.0, 449.0, 2486.0, 987.0]}

**示例8（获取tick数据）：** 

**1只股票代码、count>0 时获取的tick数据类型：pandas.DataFrame（pandas 二维表格型数据结构）类型**

In [23]:
# 获取平安最新的10个tick数据
data = get_market_data(fields = ['quoter'],
                stock_code = ['000001.SZ'],
                period = 'tick',
                count = 10)

# 打印数据类型
print('1只股票代码、count>0 时获取的tick数据类型：\n', type(data))

# 显示数据
print('\n数据内容：')
data

1只股票代码、count>0 时获取的tick数据类型：
 <class 'pandas.core.frame.DataFrame'>

数据内容：

                                                              quoter
20200413 15:58:03  {'amount': 0.0, 'high': 12.71, 'lastClose': 12...
20200413 15:59:03  {'amount': 0.0, 'high': 12.71, 'lastClose': 12...
20200413 16:00:03  {'amount': 0.0, 'high': 12.71, 'lastClose': 12...
20200413 16:01:03  {'amount': 0.0, 'high': 12.71, 'lastClose': 12...
20200413 16:02:03  {'amount': 0.0, 'high': 12.71, 'lastClose': 12...
20200413 16:03:03  {'amount': 0.0, 'high': 12.71, 'lastClose': 12...
20200413 16:04:03  {'amount': 0.0, 'high': 12.71, 'lastClose': 12...
20200413 16:05:03  {'amount': 0.0, 'high': 12.71, 'lastClose': 12...
20200413 16:06:03  {'amount': 562008064.0, 'high': 12.71, 'lastCl...

**示例9（获取tick数据）：** 

**1只股票代码、使用时间段取值时获取的tick数据类型：pandas.DataFrame（pandas 二维表格型数据结构）类型**

In [24]:
# 注意：目前本地只能补充一周的tick数据（分笔成交数据），确保本地有数据的情况下才能获取历史tick数据，否则数据会失真

# 获取平安银行在2020413 09:25:00 - 2020325 15:01:00时间段的tick数据，时间精确到秒
data = get_market_data(fields = ['quoter'],
                stock_code = ['600000.SH'],
                start_time = '20200413092500', 
                end_time = '20200413150100', 
                period = 'tick')

# 打印数据类型
print('1只股票代码、使用时间段取值时获取的tick数据类型：\n', type(data))

# 显示数据
print('\n数据内容：')
data

1只股票代码、使用时间段取值时获取的tick数据类型：
 <class 'pandas.core.frame.DataFrame'>

数据内容：

                                                              quoter
20200413 09:25:01  {'amount': 0.0, 'high': 10.15, 'lastClose': 10...
20200413 09:25:32  {'amount': 0.0, 'high': 10.15, 'lastClose': 10...
20200413 09:26:32  {'amount': 0.0, 'high': 10.15, 'lastClose': 10...
20200413 09:27:32  {'amount': 0.0, 'high': 10.15, 'lastClose': 10...
20200413 09:28:33  {'amount': 0.0, 'high': 10.15, 'lastClose': 10...
20200413 09:29:32  {'amount': 0.0, 'high': 10.15, 'lastClose': 10...
20200413 09:30:00  {'amount': 1015.0, 'high': 10.15, 'lastClose':...
20200413 09:30:02  {'amount': 295652.0, 'high': 10.17, 'lastClose...
20200413 09:30:06  {'amount': 218605.0, 'high': 10.18, 'lastClose...
20200413 09:30:09  {'amount': 199491.0, 'high': 10.18, 'lastClose...
20200413 09:30:12  {'amount': 63110.0, 'high': 10.18, 'lastClose'...
20200413 09:30:15  {'amount': 109895.0, 'high': 10.19, 'lastClose...
20200413 09:30:18  {'amount': 243934.0, 'high': 10.21, 'lastClose...
20200413 09:30:21  {'amount': 266495.0, 'high': 10.22, 'lastClose...
20200413 09:30:24  {'amount': 22616.0, 'high': 10.22, 'lastClose'...
20200413 09:30:27  {'amount': 184954.0, 'high': 10.22, 'lastClose...
20200413 09:30:30  {'amount': 89848.0, 'high': 10.22, 'lastClose'...
20200413 09:30:33  {'amount': 60196.0, 'high': 10.22, 'lastClose'...
20200413 09:30:35  {'amount': 40762.0, 'high': 10.22, 'lastClose'...
20200413 09:30:38  {'amount': 25535.0, 'high': 10.22, 'lastClose'...
20200413 09:30:41  {'amount': 16312.0, 'high': 10.22, 'lastClose'...
20200413 09:30:44  {'amount': 92824.0, 'high': 10.22, 'lastClose'...
20200413 09:30:47  {'amount': 132819.0, 'high': 10.22, 'lastClose...
20200413 09:30:50  {'amount': 152111.0, 'high': 10.22, 'lastClose...
20200413 09:30:53  {'amount': 88795.0, 'high': 10.22, 'lastClose'...
20200413 09:30:56  {'amount': 83746.0, 'high': 10.22, 'lastClose'...
20200413 09:30:59  {'amount': 306144.0, 'high': 10.22, 'lastClose...
20200413 09:31:02  {'amount': 196988.0, 'high': 10.22, 'lastClose...
20200413 09:31:05  {'amount': 43848.0, 'high': 10.22, 'lastClose'...
20200413 09:31:08  {'amount': 125360.0, 'high': 10.22, 'lastClose...
...                                                              ...
20200413 14:58:08  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:58:14  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:58:20  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:58:23  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:58:26  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:58:29  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:58:41  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:58:44  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:58:50  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:58:53  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:58:59  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:02  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:05  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:08  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:11  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:14  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:17  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:20  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:23  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:26  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:29  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:35  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:38  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:41  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:47  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:50  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:53  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 14:59:59  {'amount': 0.0, 'high': 10.22, 'lastClose': 10...
20200413 15:00:01  {'amount': 1340859.0, 'high': 10.22, 'lastClos...
20200413 15:00:04  {'amount': 119974613.0, 'high': 10.22, 'lastCl...

[4622 rows x 1 columns]

**示例10（获取tick数据）：** 

**n只股票代码、使用时间段取值时获取的tick数据类型：pandas.Panel（pandas 三维数组结构）类型**

In [25]:
# 注意：目前本地只能补充一周的tick数据（分笔成交数据），确保本地有数据的情况下才能获取历史tick数据，否则数据会失真

# 获取平安银行在2020413 09:25:00 - 2020325 15:01:00时间段的tick数据，时间精确到秒
data = get_market_data(fields = ['quoter'],
                stock_code = ['000001.SZ', '600000.SH'],
                start_time = '20200413092500', 
                end_time = '20200413150100', 
                period = 'tick')

# 打印数据类型
print('n只股票代码、使用时间段取值时获取的tick数据类型：\n', data)

# 打印数据内容，panel 转成 dataframe 显示
print('\n数据内容：\n')
data.to_frame()

n只股票代码、使用时间段取值时获取的tick数据类型：
 <class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 8677 (major_axis) x 1 (minor_axis)
Items axis: 000001.SZ to 600000.SH
Major_axis axis: 20200413 09:25:00 to 20200413 15:00:04
Minor_axis axis: quoter to quoter

数据内容：

,,000001.SZ,600000.SH
major,minor,,
20200413 09:30:00,quoter,"{'amount': 1725169.0, 'high': 12.67, 'lastClos...","{'amount': 1015.0, 'high': 10.15, 'lastClose':..."
20200413 09:30:06,quoter,"{'amount': 781774.0, 'high': 12.67, 'lastClose...","{'amount': 218605.0, 'high': 10.18, 'lastClose..."
20200413 09:30:09,quoter,"{'amount': 159394.0, 'high': 12.67, 'lastClose...","{'amount': 199491.0, 'high': 10.18, 'lastClose..."
20200413 09:30:12,quoter,"{'amount': 238670.0, 'high': 12.67, 'lastClose...","{'amount': 63110.0, 'high': 10.18, 'lastClose'..."
20200413 09:30:15,quoter,"{'amount': 291891.0, 'high': 12.67, 'lastClose...","{'amount': 109895.0, 'high': 10.19, 'lastClose..."
20200413 09:30:18,quoter,"{'amount': 305875.0, 'high': 12.67, 'lastClose...","{'amount': 243934.0, 'high': 10.21, 'lastClose..."
20200413 09:30:21,quoter,"{'amount': 269192.0, 'high': 12.67, 'lastClose...","{'amount': 266495.0, 'high': 10.22, 'lastClose..."
20200413 09:30:24,quoter,"{'amount': 171819.0, 'high': 12.67, 'lastClose...","{'amount': 22616.0, 'high': 10.22, 'lastClose'..."
20200413 09:30:27,quoter,"{'amount': 34040.0, 'high': 12.67, 'lastClose'...","{'amount': 184954.0, 'high': 10.22, 'lastClose..."
20200413 09:30:30,quoter,"{'amount': 71991.0, 'high': 12.67, 'lastClose'...","{'amount': 89848.0, 'high': 10.22, 'lastClose'..."
20200413 09:30:33,quoter,"{'amount': 59394.0, 'high': 12.67, 'lastClose'...","{'amount': 60196.0, 'high': 10.22, 'lastClose'..."
20200413 09:32:27,quoter,"{'amount': 110032.0, 'high': 12.67, 'lastClose...","{'amount': 5095.0, 'high': 10.22, 'lastClose':..."
20200413 09:32:30,quoter,"{'amount': 157029.0, 'high': 12.67, 'lastClose...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 09:32:33,quoter,"{'amount': 216441.0, 'high': 12.67, 'lastClose...","{'amount': 201788.0, 'high': 10.22, 'lastClose..."
20200413 09:32:36,quoter,"{'amount': 179545.0, 'high': 12.67, 'lastClose...","{'amount': 9171.0, 'high': 10.22, 'lastClose':..."
20200413 09:32:39,quoter,"{'amount': 179491.0, 'high': 12.67, 'lastClose...","{'amount': 23417.0, 'high': 10.22, 'lastClose'..."
20200413 09:32:42,quoter,"{'amount': 79669.0, 'high': 12.67, 'lastClose'...","{'amount': 55046.0, 'high': 10.22, 'lastClose'..."
20200413 09:32:45,quoter,"{'amount': 73402.0, 'high': 12.67, 'lastClose'...","{'amount': 81437.0, 'high': 10.22, 'lastClose'..."
20200413 09:37:42,quoter,"{'amount': 41625.0, 'high': 12.67, 'lastClose'...","{'amount': 29522.0, 'high': 10.22, 'lastClose'..."
20200413 09:38:42,quoter,"{'amount': 141233.0, 'high': 12.67, 'lastClose...","{'amount': 29487.0, 'high': 10.22, 'lastClose'..."
20200413 09:38:45,quoter,"{'amount': 60528.0, 'high': 12.67, 'lastClose'...","{'amount': 15265.0, 'high': 10.22, 'lastClose'..."
20200413 09:38:48,quoter,"{'amount': 31520.0, 'high': 12.67, 'lastClose'...","{'amount': 5089.0, 'high': 10.22, 'lastClose':..."
20200413 09:38:51,quoter,"{'amount': 85745.0, 'high': 12.67, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 09:38:54,quoter,"{'amount': 25193.0, 'high': 12.67, 'lastClose'...","{'amount': 1017.0, 'high': 10.22, 'lastClose':..."
20200413 09:38:57,quoter,"{'amount': 81843.0, 'high': 12.67, 'lastClose'...","{'amount': 15271.0, 'high': 10.22, 'lastClose'..."
20200413 09:39:00,quoter,"{'amount': 97104.0, 'high': 12.67, 'lastClose'...","{'amount': 28480.0, 'high': 10.22, 'lastClose'..."
20200413 09:39:09,quoter,"{'amount': 47888.0, 'high': 12.67, 'lastClose'...","{'amount': 8144.0, 'high': 10.22, 'lastClose':..."
20200413 09:39:12,quoter,"{'amount': 174015.0, 'high': 12.67, 'lastClose...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 09:39:15,quoter,"{'amount': 78147.0, 'high': 12.67, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 09:39:21,quoter,"{'amount': 88265.0, 'high': 12.67, 'lastClose'...","{'amount': 35630.0, 'high': 10.22, 'lastClose'..."
...,...,...,...
20200413 14:43:39,quoter,"{'amount': 35139.0, 'high': 12.71, 'lastClose'...","{'amount': 4048.0, 'high': 10.22, 'lastClose':..."
20200413 14:43:42,quoter,"{'amount': 0.0, 'high': 12.71, 'lastClose': 12...","{'amount': 28336.0, 'high': 10.22, 'lastClose'..."
20200413 14:44:24,quoter,"{'amount': 84120.0, 'high': 12.71, 'lastClose'...","{'amount': 3036.0, 'high': 10.22, 'lastClose':..."
20200413 14:45:00,quoter,"{'amount': 35112.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:45:03,quoter,"{'amount': 2508.0, 'high': 12.71, 'lastClose':...","{'amount': 5060.0, 'high': 10.22, 'lastClose':..."
20200413 14:45:51,quoter,"{'amount': 92796.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:45:54,quoter,"{'amount': 86487.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:45:57,quoter,"{'amount': 12532.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:47:03,quoter,"{'amount': 51452.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:47:06,quoter,"{'amount': 595236.0, 'high': 12.71, 'lastClose...","{'amount': 145728.0, 'high': 10.22, 'lastClose..."
20200413 14:47:33,quoter,"{'amount': 207140.0, 'high': 12.71, 'lastClose...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:47:36,quoter,"{'amount': 52745.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:47:39,quoter,"{'amount': 1232.0, 'high': 12.71, 'lastClose':...","{'amount': 90847.0, 'high': 10.22, 'lastClose'..."
20200413 14:47:42,quoter,"{'amount': 45180.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:47:45,quoter,"{'amount': 12560.0, 'high': 12.71, 'lastClose'...","{'amount': 1012.0, 'high': 10.22, 'lastClose':..."
20200413 14:47:48,quoter,"{'amount': 5024.0, 'high': 12.71, 'lastClose':...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:47:51,quoter,"{'amount': 20095.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:47:54,quoter,"{'amount': 16328.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:47:57,quoter,"{'amount': 25120.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:48:00,quoter,"{'amount': 65311.0, 'high': 12.71, 'lastClose'...","{'amount': 35653.0, 'high': 10.22, 'lastClose'..."
20200413 14:48:06,quoter,"{'amount': 54010.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:48:21,quoter,"{'amount': 48982.0, 'high': 12.71, 'lastClose'...","{'amount': 27356.0, 'high': 10.22, 'lastClose'..."
20200413 14:48:39,quoter,"{'amount': 5023.0, 'high': 12.71, 'lastClose':...","{'amount': 92100.0, 'high': 10.22, 'lastClose'..."
20200413 14:48:45,quoter,"{'amount': 8792.0, 'high': 12.71, 'lastClose':...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:48:48,quoter,"{'amount': 58990.0, 'high': 12.71, 'lastClose'...","{'amount': 4044.0, 'high': 10.22, 'lastClose':..."
20200413 14:48:51,quoter,"{'amount': 11304.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."
20200413 14:48:54,quoter,"{'amount': 21372.0, 'high': 12.71, 'lastClose'...","{'amount': 56616.0, 'high': 10.22, 'lastClose'..."
20200413 14:49:00,quoter,"{'amount': 52751.0, 'high': 12.71, 'lastClose'...","{'amount': 32384.0, 'high': 10.22, 'lastClose'..."
20200413 14:50:12,quoter,"{'amount': 20112.0, 'high': 12.71, 'lastClose'...","{'amount': 32384.0, 'high': 10.22, 'lastClose'..."
20200413 14:57:00,quoter,"{'amount': 21387.0, 'high': 12.71, 'lastClose'...","{'amount': 0.0, 'high': 10.22, 'lastClose': 10..."

## （10）获取除权除息日和复权因子 get_divid_factors()

**用法：** get_divid_factors(stock_code, date)

**释义：** 获取除权除息日和复权因子

**参数：** 

- stock_code：str，合约代码，格式为 code.market，如 '600000.SH' 
- date：str，日期，格式为yyyymmdd，如'20190105'，需准确填写除权除息日期，否则获取数据为空；日期留空，如 get_divid_factors(stock_code, '') 则获取全部数据

**返回：** list，除权除息日的毫秒级时间戳与复权因子的列表

**示例1：**

In [26]:
# 获取平安银行的所有除权除息日时间戳和复权因子
get_divid_factors('000001.SZ', '')

{682358400000: [1.0, 0.0, 0.0, 0.0, 0.0, 0, 1.03541],
 698774400000: [0.2, 0.5, 0.0, 0.0, 0.0, 0, 1.509298],
 738172800000: [0.3, 0.35, 0.5, 0.1, 16.0, 0, 1.904761],
 773856000000: [0.5, 0.3, 0.2, 0.1, 5.0, 0, 1.599073],
 811958400000: [0.3, 0.2, 0.0, 0.0, 0.0, 0, 1.238393],
 833126400000: [0.0, 0.5, 0.5, 0.0, 0.0, 0, 2.0],
 872438400000: [0.2, 0.5, 0.0, 0.0, 0.0, 0, 1.509803],
 940176000000: [0.6, 0.0, 0.0, 0.0, 0.0, 0, 1.027186],
 973440000000: [0.0, 0.0, 0.0, 0.3, 8.0, 0, 1.14489],
 1027353600000: [0.15, 0.0, 0.0, 0.0, 0.0, 0, 1.010452],
 1064764800000: [0.15, 0.0, 0.0, 0.0, 0.0, 0, 1.016322],
 1182268800000: [0.009, 0.0, 0.0, 0.0, 0.0, 1, 1.000313],
 1225382400000: [0.0335, 0.3, 0.0, 0.0, 0.0, 0, 1.304498],
 1350576000000: [0.1, 0.0, 0.0, 0.0, 0.0, 0, 1.007462],
 1371657600000: [0.17, 0.6, 0.0, 0.0, 0.0, 0, 1.614093],
 1402502400000: [0.16, 0.0, 0.2, 0.0, 0.0, 0, 1.216942],
 1428854400000: [0.1739, 0.0, 0.2, 0.0, 0.0, 0, 1.210268],
 1466006400000: [0.153, 0.0, 0.2, 0.0, 0.0, 0, 1.218203],
 1500566400000: [0.158, 0.0, 0.0, 0.0, 0.0, 0, 1.014801],
 1531324800000: [0.136, 0.0, 0.0, 0.0, 0.0, 0, 1.016203],
 1561478400000: [0.145, 0.0, 0.0, 0.0, 0.0, 0, 1.010534]}

**示例2：**

In [27]:
# 平安银行某次除权除息日为 20190626，按照此日期取复权因子
get_divid_factors('000001.SZ', '20190626')

{682358400000: [1.0, 0.0, 0.0, 0.0, 0.0, 0, 1.03541]}

## （11）获取当前期货主力合约 get_main_contract()

**用法：** get_main_contract(codemarket)

**释义：** 获取当前期货主力合约

**参数：** 

- codemarket：合约和市场，合约格式为品种名加00，如'IF00.IF'，'ZN00.SF'

**返回：** str，合约代码

**示例：**

In [28]:
# 获取沪深300股指期货主力合约代码
get_main_contract('IF00.IF')

'IF2004'

## （12）将毫秒时间转换成日期时间 timetag_to_date_time()

**用法：** timetag_to_date_time(timetag, format)

**释义：** 将毫秒时间转换成日期时间

**参数：** 

- timetag：int，毫秒级时间戳，如1512748800000
- format：str，时间格式，'%Y-%m-%d %H:%M:%S' 等任意格式

**返回：** str，时间

**示例：**

In [29]:
# 转换毫秒级时间戳为对应时间格式
timetag_to_date_time(1512748860000, '%Y%m%d %H:%M:%S')

'20171209 00:01:00'

## （13）获取指定个股 / 合约 / 指数的 K 线（交易日）列表 get_trading_dates()

**用法：** get_trading_dates(stockcode, start_date, end_date, count, period)

**释义：** 获取指定个股 / 合约 / 指数的 K 线（交易日）列表

**参数：** 

- stockcode：str，股票代码，如 '600000.SH'

- start_date：str，开始时间，为空时不使用，如 '20170101'，'20170101000000' 

- end_date：str，结束时间，为空时默认为最新时间，如 '20170102'，'20170102000000'   

- count：int，K 线个数，必须大于 0，取包括 end_date 往前的 count 个 K 线，start_date 不为空时不使用   

- period：str，K 线类型如下：

  > '1d'：日线
  >
  > '1m'：1分钟线
  >
  > '3m'：3分钟线
  >
  > '5m'：5分钟线
  >
  > '15m'：15分钟线  
  >
  > '30m'：30分钟线
  >
  > '1h'：小时线
  >
  > '1w'：周线
  >
  > '1mon'：月线
  >
  > '1q'：季线
  >
  > '1hy'：半年线
  >
  > '1y'：年线

*注：可缺省参数：start_date，end_date

**返回：** List，K 线周期（交易日）列表，period为日线时返回 ['20170101', '20170102', ...]，其它返回['20170101010000', '20170102020000', ...]

**示例：**

In [30]:
# 获取平安银行在20170101 - 20170401时间段的日线交易日列表
get_trading_dates('000001.SZ', '20170101', '20170401', 1, '1d')

['20170103',
 '20170104',
 '20170105',
 '20170106',
 '20170109',
 '20170110',
 '20170111',
 '20170112',
 '20170113',
 '20170116',
 '20170117',
 '20170118',
 '20170119',
 '20170120',
 '20170123',
 '20170124',
 '20170125',
 '20170126',
 '20170203',
 '20170206',
 '20170207',
 '20170208',
 '20170209',
 '20170210',
 '20170213',
 '20170214',
 '20170215',
 '20170216',
 '20170217',
 '20170220',
 '20170221',
 '20170222',
 '20170223',
 '20170224',
 '20170227',
 '20170228',
 '20170301',
 '20170302',
 '20170303',
 '20170306',
 '20170307',
 '20170308',
 '20170309',
 '20170310',
 '20170313',
 '20170314',
 '20170315',
 '20170316',
 '20170317',
 '20170320',
 '20170321',
 '20170322',
 '20170323',
 '20170324',
 '20170327',
 '20170328',
 '20170329',
 '20170330',
 '20170331']

## （14）获取多因子数据 get_factor_data()

**用法1：** get_factor_data(fieldList, stockList, startDate, endDate)

**释义：** 获取多因子数据

*注：获取过期合约需要手动补充过期合约列表使用前先使用数据管理下载多因子数据，多因子库数据对照表参见 Python API 开发文档

**参数：**

- fieldList：字段列表，list，如：['Solvency_and_Capital_Structure.EquityToAsset', 'AI_market_level_forcast.stk_sw1_p_ai']

- stockList：代码列表，list，如： [‘600000.SH’,  ‘000001.SZ’]

- startDate：开始时间，string，如：'20201209'

- endDate：结束时间，string，如：'20201212'

**返回：**

函数根据stockList代码列表,startDate,endDate时间范围的大小范围不同的数据类型

- 代码列表1-时间范围为1返回： pandas.Series index=字段

- 代码列表1-时间范围为n返回： pandas.DataFrame index=时间, columns=字段

- 代码列表n-时间范围为1返回： pandas.DataFrame index=代码 ,columns=字段

- 代码列表n-时间范围为n返回： dict Key=代码,value=df(index=日期, col=因子名)

**示例：**

In [42]:
fieldList = ['Solvency_and_Capital_Structure.EquityToAsset', 'AI_market_level_forcast.stk_sw1_p_ai']
stockList = ['600000.SH', '000001.SZ']
startDate = '20201209'
endDate = '20201212'
get_factor_data(fieldList, stockList, startDate, endDate)

OrderedDict([('600000.SH',
                             EquityToAsset  stk_sw1_p_ai
              1607443200000         0.2535        0.4788
              1607529600000         0.2535        0.4797
              1607616000000         0.2535        0.4811),
             ('000001.SZ',
                             EquityToAsset  stk_sw1_p_ai
              1607443200000         0.0815        0.4788
              1607529600000         0.0815        0.4797
              1607616000000         0.0815        0.4811)])

**用法2：** get_factor_data(fieldList, stockList, startDate, endDate)

**释义：** 获取多因子数据，使用前先使用数据管理下载多因子数据，多因子库数据对照表参见 Python API 开发文档

**参数：**

- fieldList：字段列表，list，如：['Solvency_and_Capital_Structure.EquityToAsset', 'AI_market_level_forcast.stk_sw1_p_ai']

- stockList：代码列表，list，如： [‘600000.SH’,  ‘000001.SZ’]

- startDate：开始时间，string，如：'20201209'

- endDate：结束时间，string，如：'20201212'

**返回：**

函数根据stockList代码列表,startDate,endDate时间范围的大小范围不同的数据类型

- 代码列表1-时间范围为1返回： pandas.Series index=字段

- 代码列表1-时间范围为n返回： pandas.DataFrame index=时间, columns=字段

- 代码列表n-时间范围为1返回： pandas.DataFrame index=代码 ,columns=字段

- 代码列表n-时间范围为n返回： dict Key=代码,value=df(index=日期, col=因子名)

**示例：**

In [43]:
fieldList = ['Solvency_and_Capital_Structure.EquityToAsset', 'AI_market_level_forcast.stk_sw1_p_ai']
stockList = '600000.SH'
startDate = '20201209'
endDate = '20201212'
get_factor_data(fieldList, stockList, startDate, endDate)

               EquityToAsset  stk_sw1_p_ai
1607443200000         0.2535        0.4788
1607529600000         0.2535        0.4797
1607616000000         0.2535        0.4811

## （15）获取指定期权列表 get_option_list()

**用法：** get_option_list(undl_code, dedate, opttype, isavailable)

**释义：** 获取指定期权列表

*注：获取过期合约需要手动补充过期合约列表

**参数：**

- undl_code：期权标的代码,如'510300.SH'

- dedate：期权到期月或当前交易日期，"YYYYMM" 格式为期权到期月，"YYYYMMDD" 格式为获取当前日期交易的期权

- opttype：期权类型，默认值为空，如"CALL"，"PUT"，为空时认购认沽都取。

- isavailable：是否可交易，当 dedate 的格式为 "YYYYMMDD" 格式为获取当前日期交易的期权时，isavailable 为 True 时返回当前可用，为False时返回当前和历史可用

**返回：**

期权合约列表 list

**示例1：**

In [44]:
# 获取到期月份为202101的上交所510300ETF认购合约
data = get_option_list('510300.SH', '202101', "CALL")
print('202101的上交所510300ETF认购合约：\n', data)

202101的上交所510300ETF认购合约：
 ['10002935.SHO', '10002938.SHO', '10003129.SHO', '10002933.SHO', '10003117.SHO', '10003131.SHO', '10003130.SHO', '10002932.SHO', '10003128.SHO', '10002939.SHO', '10003125.SHO', '10002934.SHO', '10003127.SHO', '10002936.SHO', '10003132.SHO', '10002931.SHO', '10003031.SHO', '10003133.SHO', '10003197.SHO', '10003093.SHO', '10002937.SHO', '10003126.SHO']

**示例2：**

In [45]:
# 获取20210104当天上交所510300ETF可交易的认购合约
data = get_option_list('510300.SH', '20210104', "CALL", True)
print('20210104当天上交所510300ETF可交易的认购合约：\n', data)

20210104当天上交所510300ETF可交易的认购合约：
 ['10003067.SHO', '10002935.SHO', '10002938.SHO', '10002747.SHO', '10002933.SHO', '10003033.SHO', '10002932.SHO', '10002746.SHO', '10002939.SHO', '10003066.SHO', '10002934.SHO', '10002903.SHO', '10002936.SHO', '10002769.SHO', '10003064.SHO', '10002751.SHO', '10002764.SHO', '10003069.SHO', '10003081.SHO', '10002744.SHO', '10002749.SHO', '10003071.SHO', '10003063.SHO', '10003070.SHO', '10002931.SHO', '10002748.SHO', '10003031.SHO', '10002763.SHO', '10002745.SHO', '10003068.SHO', '10002750.SHO', '10002743.SHO', '10002937.SHO', '10003065.SHO', '10003035.SHO', '10002880.SHO', '10002881.SHO', '10002877.SHO', '10002878.SHO', '10002883.SHO', '10002885.SHO', '10002905.SHO', '10002884.SHO', '10002897.SHO', '10002879.SHO', '10002882.SHO']

**示例3：**

In [46]:
# 获取20210104当天上交所510300ETF已经上市的认购合约(包括退市)
data = get_option_list('510300.SH', '20210104', "CALL", False)
print('20210104当天上交所510300ETF已经上市的认购合约(包括退市)：\n', data)

20210104当天上交所510300ETF已经上市的认购合约(包括退市)：
 ['10002497.SHO', '10002791.SHO', '10002316.SHO', '10003067.SHO', '10002693.SHO', '10002935.SHO', '10002175.SHO', '10002837.SHO', '10002221.SHO', '10002255.SHO', '10002323.SHO', '10002357.SHO', '10002548.SHO', '10002153.SHO', '10002811.SHO', '10002140.SHO', '10002459.SHO', '10002629.SHO', '10002219.SHO', '10002700.SHO', '10002665.SHO', '10002611.SHO', '10002713.SHO', '10002178.SHO', '10002563.SHO', '10002415.SHO', '10002938.SHO', '10002545.SHO', '10002454.SHO', '10002139.SHO', '10002789.SHO', '10002663.SHO', '10002413.SHO', '10002119.SHO', '10002502.SHO', '10002381.SHO', '10002706.SHO', '10002604.SHO', '10002809.SHO', '10002550.SHO', '10002452.SHO', '10002645.SHO', '10002631.SHO', '10002747.SHO', '10002328.SHO', '10002158.SHO', '10002173.SHO', '10002933.SHO', '10002160.SHO', '10002856.SHO', '10002695.SHO', '10002609.SHO', '10002310.SHO', '10002797.SHO', '10003033.SHO', '10002351.SHO', '10002227.SHO', '10002253.SHO', '10002155.SHO', '10002121.SHO', '10002899.SHO', '10002120.SHO', '10002154.SHO', '10002649.SHO', '10002252.SHO', '10002172.SHO', '10002581.SHO', '10002932.SHO', '10002719.SHO', '10002608.SHO', '10002694.SHO', '10002796.SHO', '10002311.SHO', '10002161.SHO', '10002721.SHO', '10002551.SHO', '10002525.SHO', '10002453.SHO', '10002427.SHO', '10002159.SHO', '10002329.SHO', '10002746.SHO', '10002707.SHO', '10002699.SHO', '10002605.SHO', '10002503.SHO', '10002118.SHO', '10002651.SHO', '10002455.SHO', '10002138.SHO', '10002523.SHO', '10002603.SHO', '10002701.SHO', '10002473.SHO', '10002179.SHO', '10002939.SHO', '10002610.SHO', '10002309.SHO', '10002712.SHO', '10002549.SHO', '10002254.SHO', '10002356.SHO', '10002322.SHO', '10002135.SHO', '10002141.SHO', '10002901.SHO', '10002458.SHO', '10002317.SHO', '10002790.SHO', '10003066.SHO', '10002215.SHO', '10002496.SHO', '10002851.SHO', '10002934.SHO', '10002836.SHO', '10002174.SHO', '10002903.SHO', '10002137.SHO', '10002143.SHO', '10002124.SHO', '10002354.SHO', '10002256.SHO', '10002519.SHO', '10002176.SHO', '10002840.SHO', '10002834.SHO', '10002936.SHO', '10002769.SHO', '10002217.SHO', '10003064.SHO', '10002792.SHO', '10002389.SHO', '10002315.SHO', '10002751.SHO', '10002521.SHO', '10002457.SHO', '10002546.SHO', '10002359.SHO', '10002839.SHO', '10002764.SHO', '10003069.SHO', '10003081.SHO', '10002499.SHO', '10002573.SHO', '10002744.SHO', '10002229.SHO', '10002723.SHO', '10002621.SHO', '10002451.SHO', '10002425.SHO', '10002553.SHO', '10002607.SHO', '10002705.SHO', '10002575.SHO', '10002501.SHO', '10002122.SHO', '10002156.SHO', '10002250.SHO', '10002749.SHO', '10002352.SHO', '10002794.SHO', '10002117.SHO', '10002855.SHO', '10002583.SHO', '10002374.SHO', '10003071.SHO', '10002795.SHO', '10003063.SHO', '10003070.SHO', '10002931.SHO', '10002171.SHO', '10002833.SHO', '10002225.SHO', '10002251.SHO', '10002327.SHO', '10002353.SHO', '10002748.SHO', '10002157.SHO', '10002123.SHO', '10002429.SHO', '10003031.SHO', '10002500.SHO', '10002606.SHO', '10002383.SHO', '10002661.SHO', '10002390.SHO', '10002763.SHO', '10002717.SHO', '10002567.SHO', '10002411.SHO', '10002745.SHO', '10002647.SHO', '10002633.SHO', '10002552.SHO', '10002711.SHO', '10002667.SHO', '10002838.SHO', '10002498.SHO', '10003068.SHO', '10002456.SHO', '10002249.SHO', '10002750.SHO', '10003029.SHO', '10002635.SHO', '10002358.SHO', '10002743.SHO', '10002547.SHO', '10002431.SHO', '10002271.SHO', '10002373.SHO', '10002835.SHO', '10002841.SHO', '10002177.SHO', '10002937.SHO', '10002495.SHO', '10002409.SHO', '10003065.SHO', '10002793.SHO', '10002142.SHO', '10002136.SHO', '10002321.SHO', '10002355.SHO', '10002223.SHO', '10002257.SHO', '10002813.SHO', '10002125.SHO', '10003035.SHO', '10002880.SHO', '10002881.SHO', '10002877.SHO', '10002878.SHO', '10002883.SHO', '10002885.SHO', '10002905.SHO', '10002884.SHO', '10002897.SHO', '10002879.SHO', '10002882.SHO']

## （16）获取指定市场过期合约列表 get_his_contract_list()

**用法：** get_his_contract_list(market)

**释义：** 获取指定市场过期合约列表

*注：获取过期合约需要手动补充过期合约列表

**参数：**

- market: 市场, 如 SH, SZ, SHO, SZO, IF 等

**返回：**

list, 期权合约代码列表

**示例1：**

In [47]:
# 获取中金所过期合约列表
get_his_contract_list('IF')

['IF1105.CFFEX',
 'IC1706.CFFEX',
 'IC1604.CFFEX',
 'T1609.CFFEX',
 'IF1007.CFFEX',
 'IH1902.CFFEX',
 'IF1203.CFFEX',
 'IF1301.CFFEX',
 'IF2011.CFFEX',
 'TF1403.CFFEX',
 'IF1210.CFFEX',
 'IH1911.CFFEX',
 'TF1512.CFFEX',
 'IF2002.CFFEX',
 'IC1511.CFFEX',
 'IF1312.CFFEX',
 'IF1709.CFFEX',
 'IF1904.CFFEX',
 'IF1806.CFFEX',
 'IH2004.CFFEX',
 'IC1809.CFFEX',
 'T1906.CFFEX',
 'TF2003.CFFEX',
 'IC2102.CFFEX',
 'IF1411.CFFEX',
 'IC1609.CFFEX',
 'T1706.CFFEX',
 'IF1108.CFFEX',
 'IDX-IH.CFFEX',
 'IF1704.CFFEX',
 'IF1606.CFFEX',
 'TS1912.CFFEX',
 'IF1402.CFFEX',
 'IH1711.CFFEX',
 'IF1909.CFFEX',
 'IH2009.CFFEX',
 'IH1702.CFFEX',
 'IC1906.CFFEX',
 'T1809.CFFEX',
 'IH1506.CFFEX',
 'IC1804.CFFEX',
 'IF2009.CFFEX',
 'IF1702.CFFEX',
 'IF1506.CFFEX',
 'IF1404.CFFEX',
 'TF1306.CFFEX',
 'IC2006.CFFEX',
 'IC2104.CFFEX',
 'IH1909.CFFEX',
 'IF1208.CFFEX',
 'IF1711.CFFEX',
 'IC1509.CFFEX',
 'TS2103.CFFEX',
 'IH1606.CFFEX',
 'IH1704.CFFEX',
 'IC1802.CFFEX',
 'TF1903.CFFEX',
 'IC1811.CFFEX',
 'TF1812.CFFEX',
 'IDX-T.CFFEX',
 'TS2012.CFFEX',
 'IDX-IC.CFFEX',
 'IF2004.CFFEX',
 'IC1611.CFFEX',
 'IF1409.CFFEX',
 'IF1012.CFFEX',
 'IF1110.CFFEX',
 'TF1612.CFFEX',
 'IC1602.CFFEX',
 'TF1703.CFFEX',
 'IF1103.CFFEX',
 'T2006.CFFEX',
 'IH1806.CFFEX',
 'T1509.CFFEX',
 'IF1307.CFFEX',
 'IF1205.CFFEX',
 'IH1904.CFFEX',
 'IH2002.CFFEX',
 'IH1709.CFFEX',
 'IF1911.CFFEX',
 'IH2011.CFFEX',
 'IF1902.CFFEX',
 'T1803.CFFEX',
 'IH1708.CFFEX',
 'IH2003.CFFEX',
 'IF1812.CFFEX',
 'IF1910.CFFEX',
 'IH2101.CFFEX',
 'IH2010.CFFEX',
 'IF1801.CFFEX',
 'IF1903.CFFEX',
 'T1912.CFFEX',
 'IF1408.CFFEX',
 'IC1610.CFFEX',
 'IC1712.CFFEX',
 'IF1111.CFFEX',
 'IF2005.CFFEX',
 'IF1306.CFFEX',
 'IC1505.CFFEX',
 'IH1807.CFFEX',
 'TF1506.CFFEX',
 'IH1905.CFFEX',
 'IF1204.CFFEX',
 'IC1603.CFFEX',
 'TF2009.CFFEX',
 'IF1102.CFFEX',
 'IC1701.CFFEX',
 'IC1803.CFFEX',
 'IC1901.CFFEX',
 'IH1607.CFFEX',
 'IH1705.CFFEX',
 'IC1810.CFFEX',
 'IH1512.CFFEX',
 'IC1912.CFFEX',
 'IF1507.CFFEX',
 'T1712.CFFEX',
 'IF1405.CFFEX',
 'IF1601.CFFEX',
 'IF1703.CFFEX',
 'IF2008.CFFEX',
 'TS1906.CFFEX',
 'IF1612.CFFEX',
 'IF1209.CFFEX',
 'IH1908.CFFEX',
 'TF1409.CFFEX',
 'IC1508.CFFEX',
 'IF1710.CFFEX',
 'IC2007.CFFEX',
 'IC2105.CFFEX',
 'T1603.CFFEX',
 'IH1710.CFFEX',
 'IH1612.CFFEX',
 'IF1908.CFFEX',
 'TF1806.CFFEX',
 'IC1907.CFFEX',
 'IC1805.CFFEX',
 'IH1507.CFFEX',
 'IH1703.CFFEX',
 'TS2006.CFFEX',
 'IH2008.CFFEX',
 'IH1601.CFFEX',
 'IC1608.CFFEX',
 'TF1312.CFFEX',
 'TF1709.CFFEX',
 'IF1410.CFFEX',
 'IC2103.CFFEX',
 'IF1109.CFFEX',
 'IF1512.CFFEX',
 'IC2001.CFFEX',
 'IF1403.CFFEX',
 'IF1501.CFFEX',
 'IC2012.CFFEX',
 'IF1705.CFFEX',
 'IF1607.CFFEX',
 'IF1905.CFFEX',
 'IF1807.CFFEX',
 'IC1808.CFFEX',
 'TF1909.CFFEX',
 'IH2005.CFFEX',
 'IF1202.CFFEX',
 'IH1903.CFFEX',
 'IH1801.CFFEX',
 'IF2010.CFFEX',
 'TF1606.CFFEX',
 'IC1707.CFFEX',
 'IF1104.CFFEX',
 'T2103.CFFEX',
 'IF1006.CFFEX',
 'IC1605.CFFEX',
 'T2012.CFFEX',
 'IF2101.CFFEX',
 'IH1910.CFFEX',
 'IF1211.CFFEX',
 'IF1708.CFFEX',
 'IDX-TF.CFFEX',
 'IC1510.CFFEX',
 'IH1812.CFFEX',
 'IF2003.CFFEX',
 'IC1908.CFFEX',
 'TF1809.CFFEX',
 'IH1508.CFFEX',
 'TS2009.CFFEX',
 'IH2007.CFFEX',
 'IH2105.CFFEX',
 'IF1805.CFFEX',
 'IF1907.CFFEX',
 'IC1512.CFFEX',
 'IF2001.CFFEX',
 'IH1810.CFFEX',
 'IDX-IF.CFFEX',
 'IF1311.CFFEX',
 'IF1608.CFFEX',
 'IH1912.CFFEX',
 'IF2103.CFFEX',
 'IF1302.CFFEX',
 'IF2012.CFFEX',
 'IH1803.CFFEX',
 'IH1901.CFFEX',
 'TF1706.CFFEX',
 'IC1607.CFFEX',
 'T2003.CFFEX',
 'IF1106.CFFEX',
 'IC1705.CFFEX',
 'TF1906.CFFEX',
 'IC1807.CFFEX',
 'IH1505.CFFEX',
 'IC1905.CFFEX',
 'IH1603.CFFEX',
 'IH1701.CFFEX',
 'IH1610.CFFEX',
 'IH1712.CFFEX',
 'IF1808.CFFEX',
 'IF1503.CFFEX',
 'IC2010.CFFEX',
 'TF1303.CFFEX',
 'IF1401.CFFEX',
 'IF1605.CFFEX',
 'IF1707.CFFEX',
 'T1512.CFFEX',
 'IC1708.CFFEX',
 'TF1609.CFFEX',
 'IF1510.CFFEX',
 'IC2003.CFFEX',
 'IF1009.CFFEX',
 'IF1412.CFFEX',
 'IC2101.CFFEX',
 'IC1910.CFFEX',
 'IC1812.CFFEX',
 'IH1510.CFFEX',
 'IC1903.CFFEX',
 'IC1801.CFFEX',
 'IH1707.CFFEX',
 'IH1605.CFFEX',
 'IF1712.CFFEX',
 'IF1309.CFFEX',
 'IH1808.CFFEX',
 'TF1509.CFFEX',
 'IF1610.CFFEX',
 'TF2006.CFFEX',
 'IC2005.CFFEX',
 'T1703.CFFEX',
 'IF1407.CFFEX',
 'T1612.CFFEX',
 'IF1505.CFFEX',
 'IF1701.CFFEX',
 'IF1603.CFFEX',
 'IF1901.CFFEX',
 'IF1803.CFFEX',
 'IH2012.CFFEX',
 'T1812.CFFEX',
 'T1903.CFFEX',
 'IH1608.CFFEX',
 'IH2103.CFFEX',
 'IF1912.CFFEX',
 'IF1810.CFFEX',
 'IH2001.CFFEX',
 'IF1206.CFFEX',
 'TS1909.CFFEX',
 'IDX-TS.CFFEX',
 'IH1907.CFFEX',
 'IC1507.CFFEX',
 'TF1406.CFFEX',
 'IH1805.CFFEX',
 'IF1304.CFFEX',
 'IC1703.CFFEX',
 'IC2008.CFFEX',
 'IC1601.CFFEX',
 'IF1508.CFFEX',
 'IC1710.CFFEX',
 'IC1612.CFFEX',
 'IF1011.CFFEX',
 'IF2105.CFFEX',
 'IF2007.CFFEX',
 'IF1101.CFFEX',
 'IC2009.CFFEX',
 'IC1702.CFFEX',
 'TF1603.CFFEX',
 'IH1906.CFFEX',
 'IF1207.CFFEX',
 'IF1305.CFFEX',
 'IH1804.CFFEX',
 'IC1506.CFFEX',
 'IF2104.CFFEX',
 'IF2006.CFFEX',
 'IC1711.CFFEX',
 'IF1509.CFFEX',
 'IF1112.CFFEX',
 'IF1010.CFFEX',
 'TF1712.CFFEX',
 'TF1309.CFFEX',
 'IF1802.CFFEX',
 'IH2102.CFFEX',
 'IH1609.CFFEX',
 'IF1811.CFFEX',
 'IC2004.CFFEX',
 'T2009.CFFEX',
 'IH1809.CFFEX',
 'IF1308.CFFEX',
 'IF1611.CFFEX',
 'IF1602.CFFEX',
 'IF1406.CFFEX',
 'IF1504.CFFEX',
 'IC1911.CFFEX',
 'IH1511.CFFEX',
 'TF1912.CFFEX',
 'TS2003.CFFEX',
 'IH1706.CFFEX',
 'IH1604.CFFEX',
 'IC1902.CFFEX',
 'TF1803.CFFEX',
 'IF1604.CFFEX',
 'IF1706.CFFEX',
 'TS1812.CFFEX',
 'IC2011.CFFEX',
 'IF1502.CFFEX',
 'TF2012.CFFEX',
 'TF2103.CFFEX',
 'IC2002.CFFEX',
 'IF1511.CFFEX',
 'IC1709.CFFEX',
 'T1606.CFFEX',
 'IF1008.CFFEX',
 'TS1903.CFFEX',
 'IH1602.CFFEX',
 'IC1806.CFFEX',
 'T1909.CFFEX',
 'IC1904.CFFEX',
 'IH1611.CFFEX',
 'IF1809.CFFEX',
 'IF1310.CFFEX',
 'IH1811.CFFEX',
 'TF1412.CFFEX',
 'IF2102.CFFEX',
 'IF1212.CFFEX',
 'IF1609.CFFEX',
 'IF1005.CFFEX',
 'IC1606.CFFEX',
 'IC1704.CFFEX',
 'T1709.CFFEX',
 'IF1107.CFFEX',
 'IH1802.CFFEX',
 'IF1303.CFFEX',
 'IF1201.CFFEX',
 'TF1503.CFFEX',
 'IH2006.CFFEX',
 'IH2104.CFFEX',
 'IC1909.CFFEX',
 'IH1509.CFFEX',
 'T1806.CFFEX',
 'IF1804.CFFEX',
 'IF1906.CFFEX']

**示例2：**

In [48]:
# 获取深交所期权过期合约列表
get_his_contract_list('SHO')

['10000568.SHO',
 '10000173.SHO',
 '10002064.SHO',
 '10000107.SHO',
 '10001787.SHO',
 '10002010.SHO',
 '10001300.SHO',
 '10002926.SHO',
 '10000580.SHO',
 '10000831.SHO',
 '10002497.SHO',
 '10001374.SHO',
 '10002952.SHO',
 '10000845.SHO',
 '10003263.SHO',
 '10000933.SHO',
 '10002595.SHO',
 '10003315.SHO',
 '10001619.SHO',
 '10001202.SHO',
 '10002824.SHO',
 '10000099.SHO',
 '10000482.SHO',
 '10000947.SHO',
 '10003361.SHO',
 '10001276.SHO',
 '10002850.SHO',
 '10002166.SHO',
 '10000071.SHO',
 '10002112.SHO',
 '10002509.SHO',
 '10000005.SHO',
 '10001685.SHO',
 '10003165.SHO',
 '10001072.SHO',
 '10001469.SHO',
 '10002791.SHO',
 '10003111.SHO',
 '10001006.SHO',
 '10000686.SHO',
 '10001930.SHO',
 '10002316.SHO',
 '10000201.SHO',
 '10001481.SHO',
 '10001944.SHO',
 '10002779.SHO',
 '10002362.SHO',
 '10000275.SHO',
 '10000303.SHO',
 '10000718.SHO',
 '10001583.SHO',
 '10001198.SHO',
 '10001832.SHO',
 '10002214.SHO',
 '10000377.SHO',
 '10001846.SHO',
 '10002260.SHO',
 '10001170.SHO',
 '10003067.SHO',
 '10001104.SHO',
 '10000784.SHO',
 '10002288.SHO',
 '10002693.SHO',
 '10001923.SHO',
 '10002305.SHO',
 '10000212.SHO',
 '10000609.SHO',
 '10001492.SHO',
 '10001089.SHO',
 '10001957.SHO',
 '10002371.SHO',
 '10000266.SHO',
 '10003176.SHO',
 '10001061.SHO',
 '10002399.SHO',
 '10002782.SHO',
 '10003102.SHO',
 '10001015.SHO',
 '10000695.SHO',
 '10001163.SHO',
 '10001578.SHO',
 '10003074.SHO',
 '10001117.SHO',
 '10000797.SHO',
 '10002680.SHO',
 '10003000.SHO',
 '10000310.SHO',
 '10001590.SHO',
 '10001821.SHO',
 '10002207.SHO',
 '10000364.SHO',
 '10001855.SHO',
 '10002668.SHO',
 '10002273.SHO',
 '10001708.SHO',
 '10001313.SHO',
 '10002935.SHO',
 '10000188.SHO',
 '10000593.SHO',
 '10000822.SHO',
 '10002484.SHO',
 '10001367.SHO',
 '10002941.SHO',
 '10000856.SHO',
 '10003270.SHO',
 '10000160.SHO',
 '10002077.SHO',
 '10000114.SHO',
 '10001794.SHO',
 '10003298.SHO',
 '10002003.SHO',
 '10002418.SHO',
 '10002175.SHO',
 '10000479.SHO',
 '10000062.SHO',
 '10002101.SHO',
 '10000016.SHO',
 '10001696.SHO',
 '10000920.SHO',
 '10002586.SHO',
 '10001211.SHO',
 '10002837.SHO',
 '10000491.SHO',
 '10000954.SHO',
 '10001265.SHO',
 '10002843.SHO',
 '10001145.SHO',
 '10003052.SHO',
 '10001131.SHO',
 '10003026.SHO',
 '10000336.SHO',
 '10001807.SHO',
 '10002221.SHO',
 '10000759.SHO',
 '10000342.SHO',
 '10001873.SHO',
 '10002255.SHO',
 '10001905.SHO',
 '10002323.SHO',
 '10002738.SHO',
 '10000234.SHO',
 '10001971.SHO',
 '10002357.SHO',
 '10000240.SHO',
 '10003150.SHO',
 '10001047.SHO',
 '10001999.SHO',
 '10001428.SHO',
 '10001033.SHO',
 '10002548.SHO',
 '10002153.SHO',
 '10000044.SHO',
 '10002127.SHO',
 '10000030.SHO',
 '10000906.SHO',
 '10003320.SHO',
 '10001237.SHO',
 '10002811.SHO',
 '10000972.SHO',
 '10003354.SHO',
 '10001243.SHO',
 '10001658.SHO',
 '10001335.SHO',
 '10002913.SHO',
 '10000804.SHO',
 '10001341.SHO',
 '10002967.SHO',
 '10000870.SHO',
 '10003256.SHO',
 '10000146.SHO',
 '10002051.SHO',
 '10000132.SHO',
 '10000529.SHO',
 '10000898.SHO',
 '10002025.SHO',
 '10000915.SHO',
 '10003333.SHO',
 '10001224.SHO',
 '10002802.SHO',
 '10000961.SHO',
 '10003347.SHO',
 '10001250.SHO',
 '10002140.SHO',
 '10000057.SHO',
 '10000989.SHO',
 '10002134.SHO',
 '10000023.SHO',
 '10000438.SHO',
 '10000155.SHO',
 '10002459.SHO',
 '10002042.SHO',
 '10000121.SHO',
 '10002036.SHO',
 '10001326.SHO',
 '10002900.SHO',
 '10000817.SHO',
 '10001352.SHO',
 '10001749.SHO',
 '10002974.SHO',
 '10000863.SHO',
 '10003245.SHO',
 '10000325.SHO',
 '10001814.SHO',
 '10002232.SHO',
 '10002629.SHO',
 '10000351.SHO',
 '10001860.SHO',
 '10002246.SHO',
 '10001156.SHO',
 '10003041.SHO',
 '10001539.SHO',
 '10001122.SHO',
 '10001888.SHO',
 '10003143.SHO',
 '10001054.SHO',
 '10003137.SHO',
 '10001020.SHO',
 '10001916.SHO',
 '10002330.SHO',
 '10000227.SHO',
 '10001962.SHO',
 '10002344.SHO',
 '10000648.SHO',
 '10000253.SHO',
 '10002504.SHO',
 '10000413.SHO',
 '10000008.SHO',
 '10001293.SHO',
 '10001688.SHO',
 '10002570.SHO',
 '10000467.SHO',
 '10001660.SHO',
 '10002598.SHO',
 '10002183.SHO',
 '10001614.SHO',
 '10002829.SHO',
 '10000094.SHO',
 '10001762.SHO',
 '10001379.SHO',
 '10000848.SHO',
 '10001716.SHO',
 '10000196.SHO',
 '10002081.SHO',
 '10000511.SHO',
 '10001391.SHO',
 '10003286.SHO',
 '10002406.SHO',
 '10000565.SHO',
 '10002069.SHO',
 '10002472.SHO',
 '10001109.SHO',
 '10001512.SHO',
 '10000789.SHO',
 '10000392.SHO',
 '10002285.SHO',
 '10001566.SHO',
 '10000761.SHO',
 '10002676.SHO',
 '10000715.SHO',
 '10001195.SHO',
 '10003082.SHO',
 '10002602.SHO',
 '10002219.SHO',
 '10001949.SHO',
 '10002774.SHO',
 '10000278.SHO',
 '10000663.SHO',
 '10002700.SHO',
 '10000617.SHO',
 '10001097.SHO',
 '10002387.SHO',
 '10001410.SHO',
 '10000290.SHO',
 '10003168.SHO',
 '10001464.SHO',
 '10000369.SHO',
 '10000772.SHO',
 '10001858.SHO',
 '10002665.SHO',
 '10000706.SHO',
 '10001186.SHO',
 '10002611.SHO',
 '10001501.SHO',
 '10000381.SHO',
 '10002296.SHO',
 '10001575.SHO',
 '10003079.SHO',
 '10002394.SHO',
 '10001018.SHO',
 '10001403.SHO',
 '10000698.SHO',
 '10000283.SHO',
 '10001477.SHO',
 '10002767.SHO',
 '10000670.SHO',
 '10002713.SHO',
 '10002308.SHO',
 '10000604.SHO',
 '10001084.SHO',
 '10000959.SHO',
 '10001673.SHO',
 '10001268.SHO',
 '10002190.SHO',
 '10001607.SHO',
 '10000087.SHO',
 '10002517.SHO',
 '10000400.SHO',
 '10001280.SHO',
 '10002178.SHO',
 '10002563.SHO',
 '10000474.SHO',
 '10000502.SHO',
 '10000119.SHO',
 '10001382.SHO',
 '10001799.SHO',
 '10003295.SHO',
 '10002415.SHO',
 '10000576.SHO',
 '10002461.SHO',
 '10001771.SHO',
 '10001705.SHO',
 '10002938.SHO',
 '10000185.SHO',
 '10002489.SHO',
 '10002092.SHO',
 '10001994.SHO',
 '10003129.SHO',
 '10001425.SHO',
 '10001451.SHO',
 '10002741.SHO',
 '10000656.SHO',
 '10001908.SHO',
 '10002735.SHO',
 '10000622.SHO',
 '10000239.SHO',
 '10000754.SHO',
 '10002258.SHO',
 '10002643.SHO',
 '10000720.SHO',
 '10002637.SHO',
 '10001527.SHO',
 '10001896.SHO',
 '10001553.SHO',
 '10001148.SHO',
 '10000524.SHO',
 '10002982.SHO',
 '10002433.SHO',
 '10000895.SHO',
 '10002028.SHO',
 '10000550.SHO',
 '10002447.SHO',
 '10001757.SHO',
 '10001338.SHO',
 '10001723.SHO',
 '10000809.SHO',
 '10003359.SHO',
 '10001655.SHO',
 '10001621.SHO',
 '10002531.SHO',
 '10000997.SHO',
 '10000426.SHO',
 '10002545.SHO',
 '10000049.SHO',
 '10000452.SHO',
 '10001744.SHO',
 '10002979.SHO',
 '10001730.SHO',
 '10000537.SHO',
 '10002991.SHO',
 '10002420.SHO',
 '10000886.SHO',
 '10000158.SHO',
 '10000543.SHO',
 '10002454.SHO',
 '10002522.SHO',
 '10000984.SHO',
 '10002139.SHO',
 '10000435.SHO',
 '10002556.SHO',
 '10000441.SHO',
 '10001646.SHO',
 '10000918.SHO',
 '10001229.SHO',
 '10001632.SHO',
 '10002349.SHO',
 '10002752.SHO',
 '10000645.SHO',
 '10002726.SHO',
 '10000631.SHO',
 '10001987.SHO',
 '10001436.SHO',
 '10001442.SHO',
 '10001059.SHO',
 '10001534.SHO',
 '10001885.SHO',
 '10003038.SHO',
 '10001540.SHO',
 '10000747.SHO',
 '10002650.SHO',
 '10000733.SHO',
 '10000328.SHO',
 '10001819.SHO',
 '10002624.SHO',
 '10002761.SHO',
 '10000676.SHO',
 '10001928.SHO',
 '10002715.SHO',
 '10000219.SHO',
 '10000602.SHO',
 '10001499.SHO',
 '10001082.SHO',
 '10002392.SHO',
 '10002789.SHO',
 '10003109.SHO',
 '10001405.SHO',
 '10000285.SHO',
 '10001471.SHO',
 '10001507.SHO',
 '10000387.SHO',
 '10002290.SHO',
 '10001168.SHO',
 '10001573.SHO',
 '10000774.SHO',
 '10002663.SHO',
 '10002278.SHO',
 '10000700.SHO',
 '10001180.SHO',
 '10003097.SHO',
 '10002617.SHO',
 '10001777.SHO',
 '10001703.SHO',
 '10001318.SHO',
 '10000183.SHO',
 '10000598.SHO',
 '10000829.SHO',
 '10002094.SHO',
 '10000504.SHO',
 '10001384.SHO',
 '10003293.SHO',
 '10002008.SHO',
 '10002413.SHO',
 '10000570.SHO',
 '10002467.SHO',
 '10002511.SHO',
 '10000406.SHO',
 '10001286.SHO',
 '10002565.SHO',
 '10000472.SHO',
 '10000069.SHO',
 '10001675.SHO',
 '10002848.SHO',
 '10002196.SHO',
 '10001601.SHO',
 '10000081.SHO',
 '10000517.SHO',
 '10001397.SHO',
 '10003280.SHO',
 '10002400.SHO',
 '10000563.SHO',
 '10000178.SHO',
 '10002474.SHO',
 '10001764.SHO',
 '10002959.SHO',
 '10003268.SHO',
 '10001710.SHO',
 '10000190.SHO',
 '10002087.SHO',
 '10001666.SHO',
 '10000938.SHO',
 '10002185.SHO',
 '10001612.SHO',
 '10001209.SHO',
 '10000092.SHO',
 '10000489.SHO',
 '10002119.SHO',
 '10002502.SHO',
 '10000415.SHO',
 '10001295.SHO',
 '10002576.SHO',
 '10000461.SHO',
 '10002381.SHO',
 '10001416.SHO',
 '10000296.SHO',
 '10001079.SHO',
 '10001462.SHO',
 '10002772.SHO',
 '10002369.SHO',
 '10000665.SHO',
 '10002706.SHO',
 '10000611.SHO',
 '10001091.SHO',
 '10000767.SHO',
 '10002670.SHO',
 '10000308.SHO',
 '10000713.SHO',
 '10001588.SHO',
 '10001193.SHO',
 '10001839.SHO',
 '10003084.SHO',
 '10002604.SHO',
 '10001514.SHO',
 '10000394.SHO',
 '10002283.SHO',
 '10002698.SHO',
 '10001560.SHO',
 '10001640.SHO',
 '10003338.SHO',
 '10001634.SHO',
 '10002809.SHO',
 '10000982.SHO',
 '10002524.SHO',
 '10000028.SHO',
 '10000433.SHO',
 '10002550.SHO',
 '10000447.SHO',
 '10002997.SHO',
 '10000531.SHO',
 '10000880.SHO',
 '10002426.SHO',
 '10000545.SHO',
 '10002452.SHO',
 '10002049.SHO',
 '10001359.SHO',
 '10001742.SHO',
 '10000868.SHO',
 '10001736.SHO',
 '10000741.SHO',
 '10002656.SHO',
 '10000735.SHO',
 '10002239.SHO',
 '10002622.SHO',
 '10001532.SHO',
 '10001129.SHO',
 '10001883.SHO',
 '10001546.SHO',
 '10001981.SHO',
 '10001430.SHO',
 '10003148.SHO',
 '10001444.SHO',
 '10001969.SHO',
 '10002754.SHO',
 '10000643.SHO',
 '10000258.SHO',
 '10002720.SHO',
 '10000637.SHO',
 '10001521.SHO',
 '10001890.SHO',
 '10001555.SHO',
 '10003059.SHO',
 '10000752.SHO',
 '10000349.SHO',
 '10001878.SHO',
 '10002645.SHO',
 '10000726.SHO',
 '10002631.SHO',
 '10002747.SHO',
 '10000650.SHO',
 '10002328.SHO',
 '10002733.SHO',
 '10000624.SHO',
 '10001992.SHO',
 '10001423.SHO',
 '10001038.SHO',
 '10001457.SHO',
 '10000991.SHO',
 '10002537.SHO',
 '10000420.SHO',
 '10002543.SHO',
 '10002158.SHO',
 '10000454.SHO',
 '10000979.SHO',
 '10001248.SHO',
 '10001653.SHO',
 '10001627.SHO',
 '10001751.SHO',
 '10001725.SHO',
 '10002918.SHO',
 '10002984.SHO',
 '10000139.SHO',
 '10000522.SHO',
 '10000893.SHO',
 '10002435.SHO',
 '10000556.SHO',
 '10002441.SHO',
 '10000316.SHO',
 '10001596.SHO',
 '10001827.SHO',
 '10002201.SHO',
 '10000362.SHO',
 '10000779.SHO',
 '10001853.SHO',
 '10002275.SHO',
 '10001165.SHO',
 '10003072.SHO',
 '10001111.SHO',
 '10000791.SHO',
 '10002686.SHO',
 '10003170.SHO',
 '10001067.SHO',
 '10002784.SHO',
 '10003104.SHO',
 '10001013.SHO',
 '10001408.SHO',
 '10000693.SHO',
 '10000288.SHO',
 '10001925.SHO',
 '10003198.SHO',
 '10002718.SHO',
 '10002303.SHO',
 '10000214.SHO',
 '10001494.SHO',
 '10001951.SHO',
 '10002377.SHO',
 '10000260.SHO',
 '10002580.SHO',
 '10000926.SHO',
 '10003300.SHO',
 '10001217.SHO',
 '10000497.SHO',
 '10002831.SHO',
 '10000952.SHO',
 '10001678.SHO',
 '10001263.SHO',
 '10002845.SHO',
 '10002173.SHO',
 '10002568.SHO',
 '10000064.SHO',
 '10002107.SHO',
 '10000010.SHO',
 '10001690.SHO',
 '10000166.SHO',
 '10002071.SHO',
 '10000509.SHO',
 '10000112.SHO',
 '10001389.SHO',
 '10001792.SHO',
 '10002005.SHO',
 '10001315.SHO',
 '10000595.SHO',
 '10002933.SHO',
 '10002482.SHO',
 '10000824.SHO',
 '10002099.SHO',
 '10003202.SHO',
 '10001361.SHO',
 '10002947.SHO',
 '10000850.SHO',
 '10003276.SHO',
 '10002160.SHO',
 '10000077.SHO',
 '10002114.SHO',
 '10000418.SHO',
 '10000003.SHO',
 '10001298.SHO',
 '10001683.SHO',
 '10002593.SHO',
 '10000935.SHO',
 '10002188.SHO',
 '10001204.SHO',
 '10000484.SHO',
 '10002822.SHO',
 '10000941.SHO',
 '10003367.SHO',
 '10001270.SHO',
 '10002856.SHO',
 '10001306.SHO',
 '10000586.SHO',
 '10002920.SHO',
 '10002491.SHO',
 '10000837.SHO',
 '10001769.SHO',
 '10001372.SHO',
 '10002954.SHO',
 '10000843.SHO',
 '10003265.SHO',
 '10000175.SHO',
 '10002062.SHO',
 '10002479.SHO',
 '10000101.SHO',
 '10001781.SHO',
 '10002016.SHO',
 '10001176.SHO',
 '10003061.SHO',
 '10001102.SHO',
 '10001519.SHO',
 '10000782.SHO',
 '10000399.SHO',
 '10002695.SHO',
 '10000305.SHO',
 '10001585.SHO',
 '10001834.SHO',
 '10003089.SHO',
 '10002609.SHO',
 '10002212.SHO',
 '10000371.SHO',
 '10001840.SHO',
 '10002266.SHO',
 '10001936.SHO',
 '10002310.SHO',
 '10000207.SHO',
 '10001487.SHO',
 '10001942.SHO',
 '10002364.SHO',
 '10000273.SHO',
 '10000668.SHO',
 '10003163.SHO',
 '10001074.SHO',
 '10002797.SHO',
 '10003117.SHO',
 '10001000.SHO',
 '10000680.SHO',
 '10001320.SHO',
 '10000811.SHO',
 '10001354.SHO',
 '10002972.SHO',
 '10000865.SHO',
 '10003243.SHO',
 '10000153.SHO',
 '10000548.SHO',
 '10002044.SHO',
 '10000127.SHO',
 '10002030.SHO',
 '10002146.SHO',
 '10000051.SHO',
 '10002529.SHO',
 '10002132.SHO',
 '10000025.SHO',
 '10000913.SHO',
 '10003335.SHO',
 '10001222.SHO',
 '10001639.SHO',
 '10002804.SHO',
 '10000967.SHO',
 '10003341.SHO',
 '10001256.SHO',
 '10001910.SHO',
 '10002336.SHO',
 '10000221.SHO',
 '10001964.SHO',
 '10002342.SHO',
 '10002759.SHO',
 '10000255.SHO',
 '10003145.SHO',
 '10001449.SHO',
 '10001052.SHO',
 '10003131.SHO',
 '10001026.SHO',
 '10001150.SHO',
 '10003047.SHO',
 '10001124.SHO',
 '10003033.SHO',
 '10000738.SHO',
 '10000323.SHO',
 '10001812.SHO',
 '10002234.SHO',
 '10000357.SHO',
 '10001866.SHO',
 '10002240.SHO',
 '10003156.SHO',
 '10001041.SHO',
 '10003122.SHO',
 '10001035.SHO',
 '10001903.SHO',
 '10002325.SHO',
 '10000629.SHO',
 '10000232.SHO',
 '10001977.SHO',
 '10002351.SHO',
 '10000246.SHO',
 '10000330.SHO',
 '10001801.SHO',
 '10002227.SHO',
 '10000344.SHO',
 '10001875.SHO',
 '10002253.SHO',
 '10002648.SHO',
 '10001558.SHO',
 '10001143.SHO',
 '10003054.SHO',
 '10001137.SHO',
 '10000140.SHO',
 '10002057.SHO',
 '10002989.SHO',
 '10000134.SHO',
 '10002438.SHO',
 '10002023.SHO',
 '10001333.SHO',
 '10001728.SHO',
 '10002915.SHO',
 '10000802.SHO',
 '10001347.SHO',
 '10002961.SHO',
 '10000876.SHO',
 '10000900.SHO',
 '10003326.SHO',
 '10001231.SHO',
 '10002817.SHO',
 '10000974.SHO',
 '10003352.SHO',
 '10001245.SHO',
 '10002155.SHO',
 '10000042.SHO',
 '10000459.SHO',
 '10002121.SHO',
 '10000036.SHO',
 '10003130.SHO',
 '10001027.SHO',
 '10003144.SHO',
 '10001053.SHO',
 '10001448.SHO',
 '10002758.SHO',
 '10002343.SHO',
 '10001965.SHO',
 '10000254.SHO',
 '10002337.SHO',
 '10001911.SHO',
 '10000220.SHO',
 '10000356.SHO',
 '10002241.SHO',
 '10001867.SHO',
 '10000322.SHO',
 '10000739.SHO',
 '10002235.SHO',
 '10001813.SHO',
 '10001125.SHO',
 '10003032.SHO',
 '10001151.SHO',
 '10003046.SHO',
 '10000126.SHO',
 '10002031.SHO',
 '10000549.SHO',
 '10000152.SHO',
 '10002045.SHO',
 '10002973.SHO',
 '10001355.SHO',
 '10000864.SHO',
 '10002907.SHO',
 '10001321.SHO',
 '10000810.SHO',
 '10003340.SHO',
 '10000966.SHO',
 '10001257.SHO',
 '10003334.SHO',
 '10000912.SHO',
 '10002805.SHO',
 '10001638.SHO',
 '10001223.SHO',
 '10002133.SHO',
 '10002528.SHO',
 '10002899.SHO',
 '10000024.SHO',
 '10002147.SHO',
 '10000050.SHO',
 '10002960.SHO',
 '10001346.SHO',
 '10000877.SHO',
 '10002914.SHO',
 '10001729.SHO',
 '10001332.SHO',
 '10000803.SHO',
 '10002988.SHO',
 '10000135.SHO',
 '10002022.SHO',
 '10002439.SHO',
 '10000141.SHO',
 '10002056.SHO',
 '10002120.SHO',
 '10000037.SHO',
 '10002154.SHO',
 '10000458.SHO',
 '10000043.SHO',
 '10003353.SHO',
 '10000975.SHO',
 '10001244.SHO',
 '10003327.SHO',
 '10000901.SHO',
 '10002816.SHO',
 '10001230.SHO',
 '10002350.SHO',
 '10001976.SHO',
 '10000247.SHO',
 '10002324.SHO',
 '10001902.SHO',
 '10000233.SHO',
 '10000628.SHO',
 '10001034.SHO',
 '10003157.SHO',
 '10001040.SHO',
 '10001136.SHO',
 '10003021.SHO',
 '10001142.SHO',
 '10001559.SHO',
 '10003055.SHO',
 '10000345.SHO',
 '10002649.SHO',
 '10002252.SHO',
 '10001874.SHO',
 '10000331.SHO',
 '10002226.SHO',
 '10001800.SHO',
 '10002106.SHO',
 '10001691.SHO',
 '10000011.SHO',
 '10002569.SHO',
 '10002172.SHO',
 '10000065.SHO',
 '10000953.SHO',
 '10002844.SHO',
 '10001262.SHO',
 '10001679.SHO',
 '10003301.SHO',
 '10000927.SHO',
 '10002581.SHO',
 '10002830.SHO',
 '10000496.SHO',
 '10001216.SHO',
 '10002946.SHO',
 '10001360.SHO',
 '10003277.SHO',
 '10000851.SHO',
 '10002932.SHO',
 '10000594.SHO',
 '10001314.SHO',
 '10000825.SHO',
 '10002098.SHO',
 '10002483.SHO',
 '10001793.SHO',
 '10001388.SHO',
 '10000113.SHO',
 '10000508.SHO',
 '10002004.SHO',
 '10000167.SHO',
 '10002070.SHO',
 '10000790.SHO',
 '10001110.SHO',
 '10002687.SHO',
 '10001164.SHO',
 '10003073.SHO',
 '10000778.SHO',
 '10000363.SHO',
 '10002274.SHO',
 '10001852.SHO',
 '10001597.SHO',
 '10000317.SHO',
 '10002200.SHO',
 '10001826.SHO',
 '10002376.SHO',
 '10001950.SHO',
 '10000261.SHO',
 '10002302.SHO',
 '10002719.SHO',
 '10001924.SHO',
 '10003199.SHO',
 '10001495.SHO',
 '10000215.SHO',
 '10003105.SHO',
 '10002785.SHO',
 '10000289.SHO',
 '10000692.SHO',
 '10001409.SHO',
 '10001012.SHO',
 '10003171.SHO',
 '10001066.SHO',
 '10000370.SHO',
 '10002267.SHO',
 '10001841.SHO',
 '10001584.SHO',
 '10000304.SHO',
 '10002213.SHO',
 '10002608.SHO',
 '10001835.SHO',
 '10003088.SHO',
 '10000398.SHO',
 '10000783.SHO',
 '10001518.SHO',
 '10001103.SHO',
 '10002694.SHO',
 '10001177.SHO',
 '10003060.SHO',
 '10002796.SHO',
 '10000681.SHO',
 '10001001.SHO',
 '10003162.SHO',
 '10001075.SHO',
 '10002365.SHO',
 '10001943.SHO',
 '10000669.SHO',
 '10000272.SHO',
 '10002311.SHO',
 '10001937.SHO',
 '10001486.SHO',
 '10000206.SHO',
 '10003366.SHO',
 '10000940.SHO',
 '10002857.SHO',
 '10001271.SHO',
 '10000934.SHO',
 '10002189.SHO',
 '10002592.SHO',
 '10002823.SHO',
 ...]

## （17）根据代码获取合约详细信息 get_instrumentdetail()

**用法：** get_instrumentdetail(stockcode)

**释义：** 根据代码获取合约详细信息

**参数：**

- stockcode：string，股票代码，如'600000.SH' 

**返回：** 根据stockcode返回一个dict，该字典数据key值有：

> ExchangeID：合约市场代码
>
> InstrumentID：合约代码
>
> InstrumentName：合约名称
>
> ProductID：合约的品种ID(期货)
>
> ProductName：合约的品种名称(期货)
>
> CreateDate：上市日期(期货)
>
> OpenDate：IPO日期(股票)
>
> ExpireDate：退市日或者到期日
>
> PreClose：前收盘价格
>
> SettlementPrice：前结算价格
>
> UpStopPrice：当日涨停价
>
> DownStopPrice：当日跌停价
>
> FloatVolumn：流通股本
>
> TotalVolumn：总股本
>
> LongMarginRatio：多头保证金率
>
> ShortMarginRatio：空头保证金率
>
> PriceTick：最小变价单位
>
> VolumeMultiple：合约乘数(对期货以外的品种，默认是1)
>
> MainContract：主力合约标记
>
> LastVolume：昨日持仓量
>
> InstrumentStatus：合约停牌状态
>
> IsTrading：合约是否可交易
>
> IsRecent：是否是近月合约

**示例：**

In [49]:
# 获取浦发银行股票详细信息
get_instrumentdetail('600000.SH')

{'ExchangeID': 'SH',
 'InstrumentID': '600000',
 'InstrumentName': '浦发银行',
 'Abbreviation': '',
 'ProductID': '600000',
 'CreateDate': 19991110,
 'ProductName': '浦发银行',
 'OpenDate': 19901219,
 'ExpireDate': 20991231,
 'PreClose': 10.23,
 'SettlementPrice': 0.0,
 'UpStopPrice': 11.25,
 'DownStopPrice': 9.21,
 'FloatVolumn': 29352144412.0,
 'TotalVolumn': 29352144412.0,
 'AccumulatedInterest': 1.7976931348623157e+308,
 'LongMarginRatio': 1.7976931348623157e+308,
 'ShortMarginRatio': 1.7976931348623157e+308,
 'PriceTick': 0.01,
 'VolumeMultiple': 1,
 'MainContract': 2147483647,
 'MaxMarketOrderVolume': 1000000,
 'MinMarketOrderVolume': 0,
 'MaxLimitOrderVolume': 1000000,
 'MinLimitOrderVolume': 0,
 'MaxMarginSideAlgorithm': 49,
 'DayCountFromIPO': 2147483647,
 'LastVolume': 0,
 'InstrumentStatus': 0,
 'IsTrading': False,
 'IsRecent': False,
 'ExtendInfo': {'OptUnit': 1.7976931348623157e+308,
  'MarginUnit': 1.7976931348623157e+308,
  'OptUndlCode': '',
  'OptUndlMarket': '',
  'OptLotSize': 2147483647,
  'OptExercisePrice': 1.7976931348623157e+308,
  'NeeqExeType': 2147483647,
  'OptExchFixedMargin': 1.7976931348623157e+308,
  'OptExchMiniMargin': 1.7976931348623157e+308,
  'Ccy': '',
  'IbSecType': '',
  'OptUndlRiskFreeRate': 1.7976931348623157e+308,
  'OptUndlHistoryRate': 1.7976931348623157e+308,
  'EndDelivDate': 0,
  'RegisteredCapital': 2147483647,
  'MaxOrderPriceRange': 1.7976931348623157e+308,
  'MinOrderPriceRange': 1.7976931348623157e+308,
  'VoteRightRatio': 1.0,
  'MaxMarketSellOrderVolume': 1000000,
  'MinMarketSellOrderVolume': 1,
  'MaxLimitSellOrderVolume': 1000000,
  'MinLimitSellOrderVolume': 1,
  'optType': ''}}

## （18）获取指定期权品种的详细信息 get_option_detail_data()

**用法：** get_option_detail_data(optioncode)

**释义：** 获取指定期权品种的详细信息

**参数：** 

- optioncode：期权代码，如'10001506.SHO'

**返回：** 根据optioncode返回一个dict，该字典数据key值有：

  > ExchangeID：期权市场代码
  >
  > InstrumentID：期权代码
  >
  > ProductID：期权标的的产品ID
  >
  > OpenDate：发行日期
  >
  > ExpireDate：到期日
  >
  > PreClose：前收价格
  >
  > SettlementPrice：前结算价格
  >
  > UpStopPrice：当日涨停价
  >
  > DownStopPrice：当日跌停价
  >
  > LongMarginRatio：多头保证金率
  >
  > ShortMarginRatio：空头保证金率
  >
  > PriceTick：最小变价单位
  >
  > VolumeMultiple：合约乘数
  >
  > MaxMarketOrderVolume：涨跌停价最大下单量
  >
  > MinMarketOrderVolume：涨跌停价最小下单量
  >
  > MaxLimitOrderVolume：限价单最大下单量
  >
  > MinLimitOrderVolume：限价单最小下单量
  >
  > OptUnit：期权合约单位
  >
  > MarginUnit：期权单位保证金
  >
  > OptUndlCode：期权标的证券代码
  >
  > OptUndlMarket：期权标的证券市场
  >
  > OptExercisePrice：期权行权价
  >
  > NeeqExeType：全国股转转让类型
  >
  > OptUndlRiskFreeRate：期权标的无风险利率
  >
  > OptUndlHistoryRate：期权标的历史波动率
  >
  > EndDelivDate：期权行权终止日
  >
  > optType：期权类型,CALL或PUT

**示例：**

In [50]:
get_option_detail_data('10001506.SHO')

{'ExchangeID': 'SHO',
 'InstrumentID': '10001506',
 'ProductID': '(510050)',
 'OpenDate': 20181025,
 'ExpireDate': 20190626,
 'PreClose': 1.7976931348623157e+308,
 'SettlementPrice': 1.7976931348623157e+308,
 'UpStopPrice': 1.7976931348623157e+308,
 'DownStopPrice': 1.7976931348623157e+308,
 'LongMarginRatio': 1.7976931348623157e+308,
 'ShortMarginRatio': 1.7976931348623157e+308,
 'PriceTick': 1.7976931348623157e+308,
 'VolumeMultiple': 1,
 'MaxMarketOrderVolume': 1000000,
 'MinMarketOrderVolume': 1,
 'MaxLimitOrderVolume': 1000000,
 'MinLimitOrderVolume': 1,
 'OptUnit': 1.7976931348623157e+308,
 'MarginUnit': 1.7976931348623157e+308,
 'OptUndlCode': '510050',
 'OptUndlMarket': 'SH',
 'OptExercisePrice': 1.7976931348623157e+308,
 'OptUndlRiskFreeRate': 1.7976931348623156e+306,
 'NeeqExeType': 2147483647,
 'OptUndlHistoryRate': 1.7976931348623157e+308,
 'EndDelivDate': 8247344642113365363,
 'optType': 'CALL'}

## （19）获取指定期权品种的实时隐含波动率 get_option_iv()

**用法：** get_option_iv(optioncode)

**释义：** 获取股票期权的实时隐含波动率

**参数：**

- optioncode：期权代码，如 '10003280.SHO'

**返回：**

double

**示例：**

In [51]:
get_option_iv('10003210.SHO')

0.2068920135498047

## （20）基于BS模型计算欧式期权理论价格 bsm_price()

**用法：** bsm_price(optionType, objectPrices, strikePrice, riskFree, sigma, days, dividend)

**释义：** 基于 Black-Scholes-Merton 模型，输入期权标的价格、期权行权价、无风险利率、期权标的年化波动率、剩余天数、标的分红率、计算期权的理论价格

**参数：**

- optionType：期权类型，认购：'C'，认沽：'P'

- objectPrices：期权标的价格，可以是价格列表或者单个价格

- strikePrice：期权行权价

- riskFree：无风险收益率

- sigma：标的波动率

- days：剩余天数

- dividend：分红率

**返回：**

- objectPrices 为 float 时，返回 float

- objectPrices 为 list 时，返回 list

计算结果最小值0.0001，结果保留4位小数，输入非法参数返回 nan

**示例：**

In [52]:
import numpy as np

object_prices = list(np.arange(3,4,0.01))

# 计算剩余15天的行权价3.5的认购期权,在无风险利率3%,分红率为0,标的年化波动率为23%时标的价格从3元到4元变动过程中期权理论价格序列
bsm_price('C',object_prices,3.5,0.03,0.23,15,0)

0.0001

**示例2：**

In [53]:
import numpy as np

object_prices = list(np.arange(3,4,0.01))

# 计算剩余15天的行权价3.5的认购期权,在无风险利率3%,分红率为0,标的年化波动率为23%时标的价格为3.51元的平值期权的理论价格
bsm_price('C',3.51,3.5,0.03,0.23,15,0)

0.0725

## （21）基于BS模型计算欧式期权隐含波动率 bsm_iv()

**用法：** bsm_iv(optionType, objectPrices, strikePrice, optionPrice, riskFree, days, dividend)

**释义：** 基于 Black-Scholes-Merton 模型，输入期权标的价格、期权行权价、期权现价、无风险利率、剩余天数、标的分红率,计算期权的隐含波动率

**参数：**

- optionType：期权类型，认购：'C'，认沽：'P'

- objectPrice：期权标的价格

- strikePrice：期权行权价

- optionPrice：期权现价

- riskFree：无风险收益率

- days：剩余天数

- dividend：分红率

**返回：**

double

**示例：**

In [54]:
# 计算剩余15天的行权价3.5的认购期权,在无风险利率3%,分红率为0时,标的现价3.51元,期权价格0.0725元时的隐含波动率
bsm_iv('C',3.51,3.5,0.0725,0.03,15)

0.2299